### ISSUE TITLE
Problem with XMLSummary

### ISSUE THREAD

**Issue by egede** [ganga-devs/ganga#1042]
A `jobs(386).subjobs(3).backend.reset()` gave the following output. 

```
    INFO     Job 387.2 Running PostProcessor hook
    WARNING  ---------- error in user/extension code ----------
    WARNING  Traceback (most recent call last):
    WARNING    File "/cvmfs/ganga.cern.ch/Ganga/install/6.6.1/python/Ganga/GPIDev/Lib/Job/Job.py", line 574, in updateStatus
    WARNING      getattr(self, state.hook)()
    WARNING    File "/cvmfs/ganga.cern.ch/Ganga/install/6.6.1/python/Ganga/GPIDev/Lib/Job/Job.py", line 790, in postprocess_hook
    WARNING      self.application.postprocess()
    WARNING    File "/cvmfs/ganga.cern.ch/Ganga/install/6.6.1/python/GangaLHCb/Lib/Applications/GaudiExec.py", line 482, in postprocess
    WARNING      XMLPostProcessor.GaudiExecPostProcess(self, logger)
    WARNING    File "/cvmfs/ganga.cern.ch/Ganga/install/6.6.1/python/GangaLHCb/Lib/Applications/XMLPostProcessor.py", line 85, in GaudiExecPostProcess
    WARNING      sjSummary =  GaudiXMLSummary(j, 'summary.xml').summary()
    WARNING    File "/cvmfs/ganga.cern.ch/Ganga/install/6.6.1/python/GangaGaudi/Lib/Applications/GaudiXMLSummary.py", line 50, in __init__
    WARNING      self.create(job, file)
    WARNING    File "/cvmfs/ganga.cern.ch/Ganga/install/6.6.1/python/GangaGaudi/Lib/Applications/GaudiXMLSummary.py", line 103, in create
    WARNING      self._setEnvVar(job.application)
    WARNING    File "/cvmfs/ganga.cern.ch/Ganga/install/6.6.1/python/GangaGaudi/Lib/Applications/GaudiXMLSummary.py", line 109, in _setEnvVar
    WARNING      self.env_var = gaudi_env['XMLSUMMARYBASEROOT']
    WARNING  TypeError: 'NoneType' object has no attribute '__getitem__'
    WARNING  --------------------------------------------------
    WARNING  An error occured finalising job: 387.2
    WARNING  Attemting again (2 of 5) after 2.5-sec delay
    INFO     15.49s taken to download output from DIRAC for Job 387.1
    INFO     Job 387.1 Running PostProcessor hook
```

I suspect that it is related to the recent changes in https://github.com/ganga-devs/ganga/blob/develop/python/GangaLHCb/Lib/Applications/XMLPostProcessor.py .

**Comment by mesmith75** [comment]
Do you know how the job was submitted? Was it with an old version of ganga before those changes?

**Comment by egede** [comment]
@VanyaBelyaev The problem is caused by a lacking migration in the `BenderBox` application.

**Comment by VanyaBelyaev** [comment]
Hi Ulrik, thank you!
we'll try to fix it asap. 
Are there some hints/instructions?   ( @VladimirRomanovsky )

**Comment by egede** [comment]
I think that it is a straight forward fix for @mesmith75 to do.

**Comment by VanyaBelyaev** [comment]
oh, it would be great:-)  @mesmith75 Mark, I owe you a beer, when you at CERN!

**Comment by mesmith75** [comment]
Yes I think this just needs a small modification due to the change in the postprocessor. I'll take a look.

**Comment by mesmith75** [comment]
So this is because the job was submitted with an old version of ganga but finalised with the new version so the necessary environment variable that points to the script for merging the XML summary has not been attached to the application object. I'll add in a check and a default value so that the XML should still be merged.
