### ISSUE TITLE
Incomprehensible error in DiracFile put

### ISSUE THREAD

**Issue by mesmith75** [ganga-devs/ganga#1066]
If a put fails in DiracFile users are getting errors like
```python
INFO     Uploading file '/tmp/__conf-59072333-51b8-4896-89a0-8e08eb561d3f.tgz' to 'SARA-USER' as '/lhcb/user/j/jarnauro/GangaInputFile/Job_1/__conf-59072333-51b8-4896-89a0-8e08eb561d3f.tgz'
WARNING  ---------- error in user/extension code ----------
WARNING  Traceback (most recent call last):
WARNING    File "/cvmfs/ganga.cern.ch/Ganga/install/6.6.3/python/Ganga/GPIDev/Lib/Job/Job.py", line 1498, in submit
WARNING      jobmasterconfig = self._getJobMasterConfig()
WARNING    File "/cvmfs/ganga.cern.ch/Ganga/install/6.6.3/python/Ganga/GPIDev/Lib/Job/Job.py", line 1196, in _getJobMasterConfig
WARNING      jobmasterconfig = rtHandler.master_prepare(self.application, appmasterconfig)
WARNING    File "/cvmfs/ganga.cern.ch/Ganga/install/6.6.3/python/GangaLHCb/Lib/RTHandlers/GaudiExecRTHandlers.py", line 403, in master_prepare
WARNING      generateDiracInput(app)
WARNING    File "/cvmfs/ganga.cern.ch/Ganga/install/6.6.3/python/GangaLHCb/Lib/RTHandlers/GaudiExecRTHandlers.py", line 268, in generateDiracInput
WARNING      new_df = uploadLocalFile(job, os.path.basename(compressed_file), tmp_dir)
WARNING    File "/cvmfs/ganga.cern.ch/Ganga/install/6.6.3/python/GangaLHCb/Lib/RTHandlers/GaudiExecRTHandlers.py", line 362, in uploadLocalFile
WARNING      returnable = new_df.put(force=True, uploadSE=SE, lfn=new_lfn)[0]
WARNING    File "/cvmfs/ganga.cern.ch/Ganga/install/6.6.3/python/Ganga/GPIDev/Credentials/__init__.py", line 44, in cred_wrapped_method
WARNING      return method(self, *args, **kwargs)
WARNING    File "/cvmfs/ganga.cern.ch/Ganga/install/6.6.3/python/GangaDirac/Lib/Files/DiracFile.py", line 686, in put
WARNING      stdout_temp = stdout.get('Successful')
WARNING  AttributeError: 'str' object has no attribute 'get'
WARNING  --------------------------------------------------
ERROR    'str' object has no attribute 'get' ... reverting job 1 to the new status
INFO     job 1 status changed to "new"
JobError: Error: 'str' object has no attribute 'get'
(consider --debug option for more information)
```

I think we are not properly catching an exception here.

**Comment by rob-c** [comment]
This looks like bad use of the new changes to the DIRAC API I put in for 6.3
The code should either be written to ask for a full dictionary back and then process it itself or it should just ask for a value to be returned and let the framework handle raising exceptions correctly (strongly preferred).

It shouldn't mix and match.

**Comment by mesmith75** [comment]
I couldn't reproduce this - the only way I can see that you don't get a dict here is if even the try doesn't happen. I think the user has done something truly weird with their credential.

I'll close this.

**Comment by rob-c** [comment]
@mesmith75 Shouldn't there then be a better check for a valid credential in execute (https://github.com/ganga-devs/ganga/blob/develop/python/GangaDirac/Lib/Utilities/DiracUtilities.py#L164) rather than checking if a location exists there should probably be a lifetime/universal check of if the credential is valid and an exception thrown to avoid errors like this.

**Comment by mesmith75** [comment]
That is a good idea - although I'm not sure it was the problem in this case.

**Comment by rob-c** [comment]
@mesmith75 Is this a bug in DiracFile or the proxy being invalid then?
