### ISSUE TITLE
EOFerror in execute

### ISSUE THREAD

**Issue by mesmith75** [ganga-devs/ganga#1220]
A user is experiencing problems with `DiracFile.put()`. I have tracked the issue down to the unpickling of the stdout at https://github.com/ganga-devs/ganga/blob/c483fa6dfbfa15f17ca512e92cb70bb855965273/ganga/GangaCore/Utility/execute.py#L97

This is giving an `EOFError`:
```python
Exception in thread Thread-6:
Traceback (most recent call last):
  File "/cvmfs/lhcb.cern.ch/lib/lcg/releases/LCG_88/Python/2.7.13/x86_64-slc6-gcc49-opt/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/cvmfs/lhcb.cern.ch/lib/lcg/releases/LCG_88/Python/2.7.13/x86_64-slc6-gcc49-opt/lib/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/afs/cern.ch/user/m/masmith/cmtuser/GANGA/GANGA_HEAD/install/ganga/ganga/GangaCore/Utility/execute.py", line 101, in __reader
    raise err
EOFError
```

Other DiracFile functions seem to execute fine, as does a request to `put` that should fail (i.e. if the file already exists on the grid).

I have no idea what could be causing this and no one else seems to be having the same issue. Does anyone have any clues?

**Comment by mesmith75** [comment]
nevermind - was an environment/cache issue.
