### ISSUE TITLE
Registry checker fails if a postprocess runs

### ISSUE THREAD

**Issue by mesmith75** [ganga-devs/ganga#1244]
The registry checker at startup #1193 causes a problem if it finds a job and puts it into completing. The postprocessor then runs which for a Dirac job causes problems because Dirac has not been loaded yet:

```python
ERROR    'DiracEnvSource' config variable empty
ERROR    'DiracEnvSource' config variable empty
ERROR    'DiracEnvSource' config variable empty
ERROR    None  None
ERROR    None  None
ERROR    None  None
WARNING  Required credential [DiracProxy(group='lhcb_user')] not found in store
ERROR    'DiracEnvSource' config variable empty
ERROR    'DiracEnvSource' config variable empty
ERROR    'DiracEnvSource' config variable empty
ERROR    None  None
ERROR    None  None
ERROR    None  None
WARNING  ---------- error in user/extension code ----------
WARNING  Traceback (most recent call last):
WARNING    File "/afs/cern.ch/user/m/masmith/cmtuser/GANGA/GANGA_HEAD/install/ganga/ganga/GangaCore/GPIDev/Lib/Job/Job.py", line 575, in updateStatus
WARNING      getattr(self, state.hook)()
WARNING    File "/afs/cern.ch/user/m/masmith/cmtuser/GANGA/GANGA_HEAD/install/ganga/ganga/GangaCore/GPIDev/Lib/Job/Job.py", line 791, in postprocess_hook
WARNING      self.application.postprocess()
WARNING    File "/afs/cern.ch/user/m/masmith/cmtuser/GANGA/GANGA_HEAD/install/ganga/ganga/GangaLHCb/Lib/Applications/GaudiExec.py", line 490, in postprocess
WARNING      self.removeUploadedReplicas()
WARNING    File "/afs/cern.ch/user/m/masmith/cmtuser/GANGA/GANGA_HEAD/install/ganga/ganga/GangaLHCb/Lib/Applications/GaudiExec.py", line 500, in removeUploadedReplicas
WARNING      self.jobScriptArchive.getReplicas()
WARNING    File "/afs/cern.ch/user/m/masmith/cmtuser/GANGA/GANGA_HEAD/install/ganga/ganga/GangaCore/GPIDev/Credentials/__init__.py", line 33, in cred_wrapped_method
WARNING      cred = credential_store.create(cred_req, create=True)
WARNING    File "/afs/cern.ch/user/m/masmith/cmtuser/GANGA/GANGA_HEAD/install/ganga/ganga/GangaCore/GPIDev/Credentials/CredentialStore.py", line 93, in create
WARNING      cred = query.info_class(query, check_file=check_file, create=create)
WARNING    File "/afs/cern.ch/user/m/masmith/cmtuser/GANGA/GANGA_HEAD/install/ganga/ganga/GangaDirac/Lib/Credentials/DiracProxy.py", line 37, in __init__
WARNING      super(DiracProxyInfo, self).__init__(requirements, check_file, create)
WARNING    File "/afs/cern.ch/user/m/masmith/cmtuser/GANGA/GANGA_HEAD/install/ganga/ganga/GangaCore/GPIDev/Credentials/VomsProxy.py", line 35, in __init__
WARNING      super(VomsProxyInfo, self).__init__(requirements, check_file, create)
WARNING    File "/afs/cern.ch/user/m/masmith/cmtuser/GANGA/GANGA_HEAD/install/ganga/ganga/GangaCore/GPIDev/Adapters/ICredentialInfo.py", line 133, in __init__
WARNING      self.create()
WARNING    File "/afs/cern.ch/user/m/masmith/cmtuser/GANGA/GANGA_HEAD/install/ganga/ganga/GangaCore/GPIDev/Adapters/ICredentialInfo.py", line 87, in retry_function
WARNING      return method(*args, **kwds)
WARNING    File "/afs/cern.ch/user/m/masmith/cmtuser/GANGA/GANGA_HEAD/install/ganga/ganga/GangaDirac/Lib/Credentials/DiracProxy.py", line 61, in create
WARNING      self.shell.env['X509_USER_PROXY'] = self.location
WARNING    File "/afs/cern.ch/user/m/masmith/cmtuser/GANGA/GANGA_HEAD/install/ganga/ganga/GangaDirac/Lib/Credentials/DiracProxy.py", line 76, in shell
WARNING      self._shell.env.update(getDiracEnv(self.initial_requirements.dirac_env))
WARNING    File "/afs/cern.ch/user/m/masmith/cmtuser/GANGA/GANGA_HEAD/install/ganga/ganga/GangaDirac/Lib/Utilities/DiracUtilities.py", line 69, in getDiracEnv
WARNING      return DIRAC_ENV[sourceFile]
WARNING  KeyError: 'default'
WARNING  --------------------------------------------------
JobStatusError: 'default'
(consider --debug option for more information)

```

**Comment by mesmith75** [comment]
It also causes issues if another defunct session holds the lockfile. This is particularly bad if the lxplus connection drops whilst jobs are submitting:
```python
WARNING  Auto-Failing job in bad state: 2622 was submitting
WARNING  To try this job again resubmit or use a backend.reset()
INFO     Forcing job 2622 to status "failed"
RegistryLockError: Could not lock 'jobs' object #2622! Object is locked by session 'lxplus028.cern.ch.15.36_Friday_06_April_2018.PID.30748 (pid jobs) since PID.30748' 
(consider --debug option for more information)

```

**Comment by rob-c** [comment]
@mesmith75 I'm a little surprised to see this. How is a job reaching the intermittent state `completing` ahead of the monitor running?
I'm assuming this is a master job which has all of it's sub-jobs completed? In which case isn't the best behaviour to force this job into a `running` state so that the monitoring will pick it up after startup has completed?

**Comment by mesmith75** [comment]
@rob-c  I think this came about from a job that was completing as ganga was killed. I think you are right that it should go back to running - I haven't been able to deliberately reproduce this so I'm not precisely sure how this came about.

The problem with the lock file I think is a bit more of an issue.

**Comment by rob-c** [comment]
Only way to deal with the broken lock files is to wait for Ganga to deem it stale and remove it or remove the lockfile by hand. We can reduce this timeout but then it causes issues where ganga may have a delayed updae of a lockfile over nfs/afs if a user has multiple sessions so it's not  a great fix if you make that change.

**Comment by mesmith75** [comment]
@rob-c I think the issue is more that the job registry check still runs even when the lock file is held by another session - it subsequently throws an error because it cannot update a job status and ganga quits. 

I think it just needs to check if the lock file is available before running the check.
