### ISSUE TITLE
Error when importing Ganga into Python session

### ISSUE THREAD

**Issue by egede** [ganga-devs/ganga#1263]
In version 7.0.2 of Ganga I see the following error in a python session

```
(ganga) [heppc47] ~/tmp/ganga % python
Python 2.7.14 (default, Mar 14 2018, 13:36:31) 
[GCC 7.3.1 20180303 (Red Hat 7.3.1-5)] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import ganga.ganga
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/egede/tmp/ganga/lib/python2.7/site-packages/ganga/ganga/__init__.py", line 12, in <module>
    from GangaCore.Core.InternalServices.ShutdownManager import _ganga_run_exitfuncs
ImportError: cannot import name _ganga_run_exitfuncs
>>> 
(ganga) [heppc47] ~/tmp/ganga % python
Python 2.7.14 (default, Mar 14 2018, 13:36:31) 
[GCC 7.3.1 20180303 (Red Hat 7.3.1-5)] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import ganga.ganga
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/egede/tmp/ganga/lib/python2.7/site-packages/ganga/ganga/__init__.py", line 12, in <module>
    from GangaCore.Core.InternalServices.ShutdownManager import _ganga_run_exitfuncs
ImportError: cannot import name _ganga_run_exitfuncs
>>> 
```

**Comment by rob-c** [comment]
Apologies this was me a while ago when adding protection from keyboard interrupts, should be a quick fix I think.
