### ISSUE TITLE
TypeError in Ganga Python3

### ISSUE THREAD

**Issue by apsknight** [ganga-devs/ganga#1286]
In [ganga_python3](https://github.com/ganga-devs/ganga/blob/ganga_python3/) branch. On installing Ganga in Python3 environment 
```bash
Traceback (most recent call last):
  File "/root/miniconda3/bin/ganga", line 61, in <module>
    Ganga.Runtime.setupGanga()
  File "/root/miniconda3/lib/python3.6/site-packages/Ganga/Runtime/__init__.py", line 19, in setupGanga
    Ganga.Runtime._prog.bootstrap(Ganga.Runtime._prog.interactive)
  File "/root/miniconda3/lib/python3.6/site-packages/Ganga/Runtime/bootstrap.py", line 908, in bootstrap
    startUpRegistries()
  File "/root/miniconda3/lib/python3.6/site-packages/Ganga/Runtime/Repository_runtime.py", line 261, in startUpRegistries
    for n, k, d in bootstrap():
  File "/root/miniconda3/lib/python3.6/site-packages/Ganga/Runtime/Repository_runtime.py", line 135, in bootstrap
    registry.startup()
  File "/root/miniconda3/lib/python3.6/site-packages/Ganga/GPIDev/Lib/Registry/JobRegistry.py", line 77, in startup
    super(JobRegistry, self).startup()
  File "/root/miniconda3/lib/python3.6/site-packages/Ganga/Core/GangaRepository/Registry.py", line 205, in decorated
    return f(self, *args, **kwargs)
  File "/root/miniconda3/lib/python3.6/site-packages/Ganga/Core/GangaRepository/Registry.py", line 625, in startup
    self.metadata.startup()
  File "/root/miniconda3/lib/python3.6/site-packages/Ganga/Core/GangaRepository/Registry.py", line 205, in decorated
    return f(self, *args, **kwargs)
  File "/root/miniconda3/lib/python3.6/site-packages/Ganga/Core/GangaRepository/Registry.py", line 631, in startup
    self.repository.startup()
  File "/root/miniconda3/lib/python3.6/site-packages/Ganga/Core/GangaRepository/GangaRepositoryXML.py", line 248, in startup
    self.sessionlock.startup()
  File "/root/miniconda3/lib/python3.6/site-packages/Ganga/Core/GangaRepository/SessionLock.py", line 261, in decorated
    return f(self, *args, **kwargs)
  File "/root/miniconda3/lib/python3.6/site-packages/Ganga/Core/GangaRepository/SessionLock.py", line 401, in startup
    self.finish_startup()
  File "/root/miniconda3/lib/python3.6/site-packages/Ganga/Core/GangaRepository/SessionLock.py", line 323, in decorated_global
    return f(self, *args, **kwds)
  File "/root/miniconda3/lib/python3.6/site-packages/Ganga/Core/GangaRepository/SessionLock.py", line 410, in finish_startup
    os.write(fd, "0")
TypeError: a bytes-like object is required, not 'str'
```

The error is due to this line:
https://github.com/ganga-devs/ganga/blob/3289fd712357c414c94c054878e3edbac840ddb0/python/Ganga/Core/GangaRepository/SessionLock.py#L410

**Comment by apsknight** [comment]
I've fixed this issue locally by modifying this line to
```python
        os.write(fd, b"0") 
```
Now, the Ganga is starting but still on loading Ganga by `import ganga` in Python3, I am receiving this warning.
```bash
WARNING  index_load Exception: a bytes-like object is required, not 'str'
```

Also, on shutdown, I'm receiving following error

```bash
Exception in thread GANGA_Update_Thread_shutdown:
Traceback (most recent call last):
  File "/root/miniconda3/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/root/miniconda3/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "/root/miniconda3/lib/python3.6/site-packages/Ganga/Core/GangaThread/GangaThreadPool.py", line 263, in __do_shutdown__
    num_alive_threads = __cnt_alive_threads__(_all_threads)
  File "/root/miniconda3/lib/python3.6/site-packages/Ganga/Core/GangaThread/GangaThreadPool.py", line 248, in __cnt_alive_threads__
    if t.isAlive():
  File "/root/miniconda3/lib/python3.6/threading.py", line 1115, in is_alive
    self._wait_for_tstate_lock(False)
  File "/root/miniconda3/lib/python3.6/threading.py", line 1074, in _wait_for_tstate_lock
    self._stop()
TypeError: 'Event' object is not callable
```

**Comment by egede** [comment]
The warning is exactly of the type that @alexanderrichards described in the meeting. For the shutdown message, I have no idea.

**Comment by egede** [comment]
@apsknight.  If you fix an issue, feel free to commit back to the branch.

**Comment by alexanderrichards** [comment]
yes this branch is a work in progress and is not fully ready yet hence no PR yet. I am working my way through the bugs (alas there are many!). If you find them and fix them before me then please commit back to this branch
