### ISSUE TITLE
Condor monitoring error

### ISSUE THREAD

**Issue by mesmith75** [ganga-devs/ganga#1354]
We sometimes get an error when monitoring Condor jobs:
```python
[20:16:02]
Ganga In [3]: ERROR    Exception raised executing 'updateMonitoringInformation' in Thread 'Backend Monitor':
Traceback (most recent call last):
  File "/afs/cern.ch/user/m/masmith/cmtuser/GANGA/GANGA_HEAD/install/ganga/ganga/GangaCore/Core/GangaThread/WorkerThreads/WorkerThreadPool.py", line 115, in __worker_thread
    result = item.command_input.function(*these_args, **item.command_input.kwargs)
  File "/afs/cern.ch/user/m/masmith/cmtuser/GANGA/GANGA_HEAD/install/ganga/ganga/GangaCore/Lib/Condor/Condor.py", line 583, in updateMonitoringInformation
    allDict[id]["status"] = Condor.statusDict[status]
KeyError: 'performing'
```

**Comment by mesmith75** [comment]
Closing for now as I cannot reliably reproduce it.
