### ISSUE TITLE
Condor job monitoring issue

### ISSUE THREAD

**Issue by ghost** [ganga-devs/ganga#1355]
After submitting jobs to Condor ( custom executables ) , when reopening ganga i see several messages of this kind : 
```python 
 ERROR    JobStatusError: time data '2018/ResidentSetSize of' does not match format '%Y/%m/%d %H:%M:%S'
INFO     Job 321.5 Running PostProcessor hook
WARNING  ---------- error in user/extension code ----------
WARNING  Traceback (most recent call last):
WARNING    File "/cvmfs/ganga.cern.ch/Ganga/install/7.1.4/lib/python2.7/site-packages/ganga/GangaCore/GPIDev/Lib/Job/Job.py", line 589, in updateStatus
WARNING      self.time.timenow(newstatus)
WARNING    File "/cvmfs/ganga.cern.ch/Ganga/install/7.1.4/lib/python2.7/site-packages/ganga/GangaCore/GPIDev/Lib/Job/JobTime.py", line 127, in timenow
WARNING      be_statetime = stripProxy(j.backend).getStateTime(childstatus)
WARNING    File "/cvmfs/ganga.cern.ch/Ganga/install/7.1.4/lib/python2.7/site-packages/ganga/GangaCore/Lib/Condor/Condor.py", line 743, in getStateTime
WARNING      if datetime.datetime.strptime(str(datetime.datetime.now().year)+'/'+splitLine[2]+' '+splitLine[3], "%Y/%m/%d %H:%M:%S") > datetime.datetime.now():
WARNING    File "/cvmfs/lhcb.cern.ch/lib/lcg/releases/Python/2.7.13-597a5/x86_64-slc6-gcc49-opt/lib/python2.7/_strptime.py", line 332, in _strptime
WARNING      (data_string, format))
WARNING  ValueError: time data '2018/ResidentSetSize of' does not match format '%Y/%m/%d %H:%M:%S'
WARNING  --------------------------------------------------
ERROR    JobStatusError: time data '2018/ResidentSetSize of' does not match format '%Y/%m/%d %H:%M:%S'
INFO     Job 321.28 Running PostProcessor hook
WARNING  ---------- error in user/extension code ----------
WARNING  Traceback (most recent call last):
WARNING    File "/cvmfs/ganga.cern.ch/Ganga/install/7.1.4/lib/python2.7/site-packages/ganga/GangaCore/GPIDev/Lib/Job/Job.py", line 589, in updateStatus
WARNING      self.time.timenow(newstatus)
WARNING    File "/cvmfs/ganga.cern.ch/Ganga/install/7.1.4/lib/python2.7/site-packages/ganga/GangaCore/GPIDev/Lib/Job/JobTime.py", line 127, in timenow
WARNING      be_statetime = stripProxy(j.backend).getStateTime(childstatus)
WARNING    File "/cvmfs/ganga.cern.ch/Ganga/install/7.1.4/lib/python2.7/site-packages/ganga/GangaCore/Lib/Condor/Condor.py", line 743, in getStateTime
WARNING      if datetime.datetime.strptime(str(datetime.datetime.now().year)+'/'+splitLine[2]+' '+splitLine[3], "%Y/%m/%d %H:%M:%S") > datetime.datetime.now():
WARNING    File "/cvmfs/lhcb.cern.ch/lib/lcg/releases/Python/2.7.13-597a5/x86_64-slc6-gcc49-opt/lib/python2.7/_strptime.py", line 332, in _strptime
WARNING      (data_string, format))
WARNING  ValueError: time data '2018/ResidentSetSize of' does not match format '%Y/%m/%d %H:%M:%S'
WARNING  --------------------------------------------------
ERROR    Empty stdout file from job 321.65 after waiting 10mins. Marking job asfailed.
```

The CondorLog file is : 
```
000 (100655.005.000) 10/02 18:58:00 Job submitted from host: <188.185.71.142:9618?addrs=188.185.71.142-9618&noUDP&sock=1316_3eb9_3>
...
001 (100655.005.000) 10/02 18:58:04 Job executing on host: <188.185.52.26:9618?addrs=188.185.52.26-9618+[--1]-9618&noUDP&sock=8887_3fd5_3>
...
006 (100655.005.000) 10/02 18:58:12 Image size of job updated: 178040
	103  -  MemoryUsage of job (MB)
	104708  -  ResidentSetSize of job (KB)
...
006 (100655.005.000) 10/02 19:03:12 Image size of job updated: 379688
	294  -  MemoryUsage of job (MB)
	300588  -  ResidentSetSize of job (KB)
...
005 (100655.005.000) 10/02 19:06:31 Job terminated.
	(1) Normal termination (return value 0)
		Usr 0 00:07:57, Sys 0 00:00:03  -  Run Remote Usage
		Usr 0 00:00:00, Sys 0 00:00:00  -  Run Local Usage
		Usr 0 00:07:57, Sys 0 00:00:03  -  Total Remote Usage
		Usr 0 00:00:00, Sys 0 00:00:00  -  Total Local Usage
	282164  -  Run Bytes Sent By Job
	6300  -  Run Bytes Received By Job
	282164  -  Total Bytes Sent By Job
	6300  -  Total Bytes Received By Job
	Partitionable Resources :    Usage  Request Allocated
	   Cpus                 :                 1         1
	   Disk (KB)            :   207274       10   2104034
	   Memory (MB)          :      294     2000      2000
...
```

**Comment by mesmith75** [comment]
Ah I can see what has gone wrong - we check for the Condor status code on a line as a string so we know which line has the end time. Unfortunately your memory size (by pure coincidence) has the status code in it (300588) so we use that line instead.

I will try and rectify it to be a little more robust.

**Comment by ghost** [comment]
@mesmith75 , thanks a lot for this. Will running ```ganga ``` on lxplus out of slc6-gcc62 will be able to pick up the fix or we should wait for a new release?

**Comment by egede** [comment]
@rquaglia90 I just approved and merged this fix. It will go into the DEV version of Ganga overnight, so from tomorrow morning you can do `ganga --ganga-version DEV`. It will be part of the next regular release as well.
