### ISSUE TITLE
GoogleFile partially broken

### ISSUE THREAD

**Issue by egede** [ganga-devs/ganga#1623]
When trying to use the GoogleFile put method I get an error due to a missing dependency

```
Ganga In [1]: g = GoogleFile()
Ganga In [2]: g.namePattern='test'
Ganga In [3]: g.localDir = '~/tmp'
Ganga In [4]: g.put()                                                                                    
ERROR    !!Unknown/Unexpected ERROR!!
:
ModuleNotFoundError: No module named 'oauth2client'
```
When just installing this module manually, I get a long list of warnings, but the code actually works.

```
Ganga In [4]: g.put()                                                                                    
WARNING  __init__() takes at most 4 positional arguments (5 given)
INFO     Go to the following link in your browser: https://accounts.google.com/o/oauth2/v2/auth?client_id=776655306197-dirtoquqsm7cpqgepvamofg5t2b5f637.apps.googleusercontent.com&redirect_uri=urn%3Aietf%3Awg%3Aoauth%3A2.0%3Aoob&scope=https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fdrive.file&access_type=offline&response_type=code
Enter verification code: 4/yAHOqQ5PXNpnpITCTi757SgAlOSiSCp8tjjN-a3bYJZjQRSEymH2OXo
INFO     Your GoogleDrive credentials have been stored in the file /home/egede/gangadir/googlecreddata.pkl and are only readable by you. The file will give permission to modify files in your GoogleDrive. Permission can be revoked by going to "Manage Apps" in your GoogleDrive or by deleting the credentials through the deleteCredentials GoogleFile method.
WARNING  file_cache is unavailable when using oauth2client >= 4.0.0 or google-auth
Traceback (most recent call last):
  File "/home/egede/programming/ganga/lib/python3.7/site-packages/googleapiclient/discovery_cache/__init__.py", line 36, in autodetect
    from google.appengine.api import memcache
ModuleNotFoundError: No module named 'google.appengine'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/egede/programming/ganga/lib/python3.7/site-packages/googleapiclient/discovery_cache/file_cache.py", line 33, in <module>
    from oauth2client.contrib.locked_file import LockedFile
ModuleNotFoundError: No module named 'oauth2client.contrib.locked_file'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/egede/programming/ganga/lib/python3.7/site-packages/googleapiclient/discovery_cache/file_cache.py", line 37, in <module>
    from oauth2client.locked_file import LockedFile
ModuleNotFoundError: No module named 'oauth2client.locked_file'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/egede/programming/ganga/lib/python3.7/site-packages/googleapiclient/discovery_cache/__init__.py", line 41, in autodetect
    from . import file_cache
  File "/home/egede/programming/ganga/lib/python3.7/site-packages/googleapiclient/discovery_cache/file_cache.py", line 41, in <module>
    'file_cache is unavailable when using oauth2client >= 4.0.0 or google-auth')
ImportError: file_cache is unavailable when using oauth2client >= 4.0.0 or google-auth
WARNING  file_cache is unavailable when using oauth2client >= 4.0.0 or google-auth
Traceback (most recent call last):
  File "/home/egede/programming/ganga/lib/python3.7/site-packages/googleapiclient/discovery_cache/__init__.py", line 36, in autodetect
    from google.appengine.api import memcache
ModuleNotFoundError: No module named 'google.appengine'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/egede/programming/ganga/lib/python3.7/site-packages/googleapiclient/discovery_cache/file_cache.py", line 33, in <module>
    from oauth2client.contrib.locked_file import LockedFile
ModuleNotFoundError: No module named 'oauth2client.contrib.locked_file'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/egede/programming/ganga/lib/python3.7/site-packages/googleapiclient/discovery_cache/file_cache.py", line 37, in <module>
    from oauth2client.locked_file import LockedFile
ModuleNotFoundError: No module named 'oauth2client.locked_file'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/egede/programming/ganga/lib/python3.7/site-packages/googleapiclient/discovery_cache/__init__.py", line 41, in autodetect
    from . import file_cache
  File "/home/egede/programming/ganga/lib/python3.7/site-packages/googleapiclient/discovery_cache/file_cache.py", line 41, in <module>
    'file_cache is unavailable when using oauth2client >= 4.0.0 or google-auth')
ImportError: file_cache is unavailable when using oauth2client >= 4.0.0 or google-auth
INFO     File 'test' uploaded succesfully
```
The two problems might be related (I see something about version of oauth2) so they probably need to be fixed together.

**Comment by DumbMachine** [comment]
The package that we are currently using [oauth2client](https://github.com/googleapis/oauth2client), seems to be archived. Current google [examples](https://developers.google.com/drive/api/v3/quickstart/python) recommend using the newer `from google_auth_oauthlib.flow import InstalledAppFlow` flow patterns. 

Should we move to use the newer python package?

**Comment by egede** [comment]
Yes, that is much better
