### ISSUE TITLE
Ganga 8.3.1 doesn't exit cleanly

### ISSUE THREAD

**Issue by NickHastings** [ganga-devs/ganga#1679]
Hi,

it seems the work to bring new UI into ganga had some negative impact on the 8.3.1 release. 

```hastings@xps ~/opt/ganga 
% ./ganga-8.3.1/bin/ganga

*** Welcome to Ganga ***
Version: 8.3.1
Documentation and support: http://cern.ch/ganga
Type help() or help('index') for online help.

This is free software (GPL), and you are welcome to redistribute it
under certain conditions; type license() for details.


INFO     reading config file /home/hastings/.gangarc
INFO     --------------------------------------------------
INFO     --------------------------------------------------
INFO     Release notes for version 'Ganga-8.3.1':
INFO     --------------------------------------------------
INFO     
INFO     --------------------------------------------------
INFO     ganga/ganga/GangaCore
INFO     --------------------------------------------------
INFO     
INFO     * Option to specify location of virutalisation binary, i.e. j.virtualization.binary='/cvmfs/atlas.cern.ch/repo/containers/sw/singularity/x86_64-el7/current/bin/singularity' . #1670
INFO     * Bugfix for container permissions #1678
INFO     * Syntax warning fixes #1674
INFO     * Fix deprecation warnings #1646
INFO     * Remove old webgui code #1677
INFO     
INFO     --------------------------------------------------
INFO     --------------------------------------------------

[11:21:30]
Ganga In [1]: exit

Error in atexit._run_exitfuncs:
Traceback (most recent call last):
  File "/home/hastings/opt/ganga/ganga-8.3.1/ganga/GangaCore/Core/InternalServices/ShutdownManager.py", line 42, in _protected_ganga_exitfuncs
    _unprotected_ganga_exitfuncs()
  File "/home/hastings/opt/ganga/ganga-8.3.1/ganga/GangaCore/Core/InternalServices/ShutdownManager.py", line 61, in _unprotected_ganga_exitfuncs
    from GangaGUI.start import stop_gui
  File "/home/hastings/opt/ganga/ganga-8.3.1/ganga/GangaGUI/start.py", line 3, in <module>
    from GangaGUI.gui import app
  File "/home/hastings/opt/ganga/ganga-8.3.1/ganga/GangaGUI/gui/__init__.py", line 1, in <module>
    from flask import Flask
ModuleNotFoundError: No module named 'flask'
%
```

The above is from a Debian 10 machine but I see the same on SL6. Please let me know if any additional information is needed.

Regards,

Nick.

**Comment by egede** [comment]
Hi Nick,

How do you install Ganga? The lastest version has a new dependency, `flask`, and it seems like it is missing for you. If you just updated the code from Git, you might not have reprocessed the dependencies.

Ulrik.

**Comment by NickHastings** [comment]
Hi,

Installed from the tar ball. Steps were:
```
wget https://github.com/ganga-devs/ganga/archive/8.3.1.tar.gz
tar xf 8.3.1.tar.gz
./ganga-8.3.1/bin/ganga
```
I didn't see any mention of new dependencies in the release notes so assumed the code that depends on flask was included in the release accidentally.
```
% python3 -m pip install flask
```
Fixed it.

Cheers,

Nick.

**Comment by egede** [comment]
Sorry for not being explicit about new dependency. In honesty, the new GUI part does essentially nothing for now, but we expect some big steps forward in the next few months. In general I would recommend to install ganga itself using pip as well.

`python3 -m pip install ganga`

**Comment by NickHastings** [comment]
Hi,

Ok, I'll use pip for ganga installation in the future. Perhaps https://ganga.readthedocs.io/en/latest/UserGuide/InstallAndBasicUsage.html
could be updated to explain that using pip is the recommend installation method (and why).

Cheers,

Nick.

**Comment by egede** [comment]
Yes, that page indeed could do with a clean-up ;-) I will file that as a new issue.

**Comment by egede** [comment]
See #1680
