### ISSUE TITLE
Deal with AFS token expiry nicely

### ISSUE THREAD

**Issue by mesmith75** [ganga-devs/ganga#1775]
When the AFS token expires ganga behaves badly:
```python
PermissionError: [Errno 13] Permission denied: '/afs/cern.ch/work/m/masmith/gangadir/repository/masmith/LocalXML/6.0/sessions/lxplus769.cern.ch.09.53_Friday_11_September_2020.PID.26759.session.tasks.locks'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/cvmfs/sft.cern.ch/lcg/releases/LCG_92python3/Python/3.6.3/x86_64-slc6-gcc62-opt/lib/python3.6/logging/handlers.py", line 71, in emit
    if self.shouldRollover(record):
  File "/cvmfs/sft.cern.ch/lcg/releases/LCG_92python3/Python/3.6.3/x86_64-slc6-gcc62-opt/lib/python3.6/logging/handlers.py", line 188, in shouldRollover
    self.stream.seek(0, 2)  #due to non-posix-compliant Windows feature
ValueError: I/O operation on closed file.
Call stack:
  File "/cvmfs/sft.cern.ch/lcg/releases/LCG_92python3/Python/3.6.3/x86_64-slc6-gcc62-opt/lib/python3.6/threading.py", line 884, in _bootstrap
    self._bootstrap_inner()
  File "/cvmfs/sft.cern.ch/lcg/releases/LCG_92python3/Python/3.6.3/x86_64-slc6-gcc62-opt/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/cvmfs/ganga.cern.ch/Ganga/install/8.3.5/lib/python3.6/site-packages/ganga/GangaCore/Core/GangaRepository/SessionLock.py", line 119, in run
    self.updateNow()
  File "/cvmfs/ganga.cern.ch/Ganga/install/8.3.5/lib/python3.6/site-packages/ganga/GangaCore/Core/GangaRepository/SessionLock.py", line 148, in updateNow
    now = self.delayedUpdateLocks(index)
  File "/cvmfs/ganga.cern.ch/Ganga/install/8.3.5/lib/python3.6/site-packages/ganga/GangaCore/Core/GangaRepository/SessionLock.py", line 157, in delayedUpdateLocks
    now = self.updateLocksNow(index)
  File "/cvmfs/ganga.cern.ch/Ganga/install/8.3.5/lib/python3.6/site-packages/ganga/GangaCore/Core/GangaRepository/SessionLock.py", line 181, in updateLocksNow
    now = self.updateLocksNow(index, failcount)
  File "/cvmfs/ganga.cern.ch/Ganga/install/8.3.5/lib/python3.6/site-packages/ganga/GangaCore/Core/GangaRepository/SessionLock.py", line 181, in updateLocksNow
    now = self.updateLocksNow(index, failcount)
  File "/cvmfs/ganga.cern.ch/Ganga/install/8.3.5/lib/python3.6/site-packages/ganga/GangaCore/Core/GangaRepository/SessionLock.py", line 181, in updateLocksNow
    now = self.updateLocksNow(index, failcount)
  File "/cvmfs/ganga.cern.ch/Ganga/install/8.3.5/lib/python3.6/site-packages/ganga/GangaCore/Core/GangaRepository/SessionLock.py", line 187, in updateLocksNow
    logger.warning("This could be due to a filesystem problem, or multiple versions of ganga trying to access the same file")
Message: 'This could be due to a filesystem problem, or multiple versions of ganga trying to access the same file'
Arguments: ()

--- Logging error ---
Traceback (most recent call last):
  File "/cvmfs/sft.cern.ch/lcg/releases/LCG_92python3/Python/3.6.3/x86_64-slc6-gcc62-opt/lib/python3.6/logging/handlers.py", line 71, in emit
    if self.shouldRollover(record):
  File "/cvmfs/sft.cern.ch/lcg/releases/LCG_92python3/Python/3.6.3/x86_64-slc6-gcc62-opt/lib/python3.6/logging/handlers.py", line 188, in shouldRollover
    self.stream.seek(0, 2)  #due to non-posix-compliant Windows feature
ValueError: I/O operation on closed file.
Call stack:
  File "/cvmfs/ganga.cern.ch/Ganga/install/LATEST/bin/ganga", line 92, in <module>
    GangaCore.Runtime._prog.run(GPI.__dict__)
  File "/cvmfs/ganga.cern.ch/Ganga/install/8.3.5/lib/python3.6/site-packages/ganga/GangaCore/Runtime/bootstrap.py", line 1129, in run
    self.launch_IPython(local_ns, GangaProgram._ganga_error_handler, self.ganga_prompt)
  File "/cvmfs/ganga.cern.ch/Ganga/install/8.3.5/lib/python3.6/site-packages/ganga/GangaCore/Runtime/bootstrap.py", line 1257, in launch_IPython
    ipshell(local_ns=local_ns, module=GangaCore.GPI)
  File "/cvmfs/ganga.cern.ch/Ganga/install/8.3.5/lib/python3.6/site-packages/IPython/terminal/embed.py", line 229, in __call__
    global_ns=global_ns, compile_flags=compile_flags)
  File "/cvmfs/ganga.cern.ch/Ganga/install/8.3.5/lib/python3.6/site-packages/IPython/terminal/embed.py", line 324, in mainloop
    self.interact()
  File "/cvmfs/ganga.cern.ch/Ganga/install/8.3.5/lib/python3.6/site-packages/IPython/terminal/interactiveshell.py", line 554, in interact
    self.run_cell(code, store_history=True)
  File "/cvmfs/ganga.cern.ch/Ganga/install/8.3.5/lib/python3.6/site-packages/IPython/core/interactiveshell.py", line 2867, in run_cell
    raw_cell, store_history, silent, shell_futures)
  File "/cvmfs/ganga.cern.ch/Ganga/install/8.3.5/lib/python3.6/site-packages/IPython/core/interactiveshell.py", line 2895, in _run_cell
    return runner(coro)
  File "/cvmfs/ganga.cern.ch/Ganga/install/8.3.5/lib/python3.6/site-packages/IPython/core/async_helpers.py", line 68, in _pseudo_sync_runner
    coro.send(None)
  File "/cvmfs/ganga.cern.ch/Ganga/install/8.3.5/lib/python3.6/site-packages/IPython/core/interactiveshell.py", line 3072, in run_cell_async
    interactivity=interactivity, compiler=compiler, result=result)
  File "/cvmfs/ganga.cern.ch/Ganga/install/8.3.5/lib/python3.6/site-packages/IPython/core/interactiveshell.py", line 3263, in run_ast_nodes
    if (await self.run_code(code, result,  async_=asy)):
  File "/cvmfs/ganga.cern.ch/Ganga/install/8.3.5/lib/python3.6/site-packages/IPython/core/interactiveshell.py", line 3343, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-6-70d44a1ac038>", line 1, in <module>
    credential_store.create(AfsToken())
  File "/cvmfs/ganga.cern.ch/Ganga/install/8.3.5/lib/python3.6/site-packages/ganga/GangaCore/GPIDev/Base/Proxy.py", line 720, in proxy_wrapped
    r = f(*s_args, **s_kwargs)
  File "/cvmfs/ganga.cern.ch/Ganga/install/8.3.5/lib/python3.6/site-packages/ganga/GangaCore/GPIDev/Credentials/CredentialStore.py", line 93, in create
    cred = query.info_class(query, check_file=check_file, create=create)
  File "/cvmfs/ganga.cern.ch/Ganga/install/8.3.5/lib/python3.6/site-packages/ganga/GangaCore/GPIDev/Credentials/AfsToken.py", line 43, in __init__
    super(AfsTokenInfo, self).__init__(requirements, check_file, create)
  File "/cvmfs/ganga.cern.ch/Ganga/install/8.3.5/lib/python3.6/site-packages/ganga/GangaCore/GPIDev/Adapters/ICredentialInfo.py", line 131, in __init__
    self.create()
  File "/cvmfs/ganga.cern.ch/Ganga/install/8.3.5/lib/python3.6/site-packages/ganga/GangaCore/GPIDev/Adapters/ICredentialInfo.py", line 86, in retry_function
    return method(*args, **kwds)
  File "/cvmfs/ganga.cern.ch/Ganga/install/8.3.5/lib/python3.6/site-packages/ganga/GangaCore/GPIDev/Credentials/AfsToken.py", line 60, in create
```
It would be nice to check the AFS token before throwing these exceptions.

**Comment by egede** [comment]
The nasty messages here happen because the logger tries to write to the file system as well. So we have

- Log file fails to write as afs token expired.
- logger tries to inform user that there is a problem.
- logger fails to write to disk as it has no write access.
- Nasty traceback emitted.

As even logging is not working correctly, it seems like Ganga should just exit. But can we force an exit from within a thread?
