### ISSUE TITLE
Error finalising a subjob

### ISSUE THREAD

**Issue by mesmith75** [ganga-devs/ganga#1809]
```python
INFO     job 1 status changed to "completing"
WARNING  ---------- error in user/extension code ----------
WARNING  Traceback (most recent call last):
WARNING    File "/afs/cern.ch/user/m/masmith/cmtuser/GANGA/GANGA_HEAD/install/ganga/ganga/GangaCore/GPIDev/Lib/Job/Job.py", line 622, in updateStatus
WARNING      if self.outputFilesFailures():
WARNING    File "/afs/cern.ch/user/m/masmith/cmtuser/GANGA/GANGA_HEAD/install/ganga/ganga/GangaCore/GPIDev/Lib/Job/Job.py", line 755, in outputFilesFailures
WARNING      for subfile in outputfile.subfiles:
WARNING  AttributeError: 'dict' object has no attribute 'subfiles'
WARNING  --------------------------------------------------
WARNING  An error occured finalising job: 1.0
WARNING  Attempting again (5 of 5) after 2.5-sec delay
ERROR    JobStatusError: 'dict' object has no attribute 'subfiles'
```
Got this error when finalising a job, never seen it before. The only interesting this is that this is with the database repository, although it may be completely unrelated.

**Comment by egede** [comment]
This looks related to the wildcards in outputfiles. I guess those subfiles are stored in a `GangaList`. I wonder if there is a problem writing that to the database?

**Comment by egede** [comment]
I wonder if we can create some kind of test to force this error?

**Comment by mesmith75** [comment]
Closing this as not able to reproduce
