### ISSUE TITLE
Prepared application submission broken

### ISSUE THREAD

**Issue by mesmith75** [ganga-devs/ganga#1897]
If I copy a job that is prepared the new application is in the prepared state. When submitting it still tries to compile the application to make the GaudiExec sandbox. This is wrong - it should be using the already prepared application in the sharedir.

```python
INFO     Requesting LFN replica info
INFO     Got Replica Info: [0:1] of 1
INFO     Got all good replicas
INFO     Calculating site<->SE Mapping
INFO     Calculating best data subsets
INFO     Average Subset size is: 1.0
INFO     File count checked! Ready to Submit
INFO     Created 1 subsets
INFO     Finished Splitting
INFO     submitting 1 subjobs
WARNING  ---------- error in user/extension code ----------
WARNING  Traceback (most recent call last):
WARNING    File "/afs/cern.ch/user/m/masmith/cmtuser/GANGA/GANGA_HEAD/install/ganga/ganga/GangaCore/GPIDev/Lib/Job/Job.py", line 1697, in submit
WARNING      jobmasterconfig = self._getJobMasterConfig()
WARNING    File "/afs/cern.ch/user/m/masmith/cmtuser/GANGA/GANGA_HEAD/install/ganga/ganga/GangaCore/GPIDev/Lib/Job/Job.py", line 1270, in _getJobMasterConfig
WARNING      jobmasterconfig = rtHandler.master_prepare(self.application, appmasterconfig)
WARNING    File "/afs/cern.ch/user/m/masmith/cmtuser/GANGA/GANGA_HEAD/install/ganga/ganga/GangaLHCb/Lib/RTHandlers/GaudiExecRTHandlers.py", line 549, in master_prepare
WARNING      generateDiracScripts(app)
WARNING    File "/afs/cern.ch/user/m/masmith/cmtuser/GANGA/GANGA_HEAD/install/ganga/ganga/GangaLHCb/Lib/RTHandlers/GaudiExecRTHandlers.py", line 389, in generateDiracScripts
WARNING      generateJobScripts(app, appendJobScripts=True)
WARNING    File "/afs/cern.ch/user/m/masmith/cmtuser/GANGA/GANGA_HEAD/install/ganga/ganga/GangaLHCb/Lib/RTHandlers/GaudiExecRTHandlers.py", line 373, in generateJobScripts
WARNING      wnScript = generateWNScript(prepareCommand(this_app), this_app)
WARNING    File "/afs/cern.ch/user/m/masmith/cmtuser/GANGA/GANGA_HEAD/install/ganga/ganga/GangaLHCb/Lib/RTHandlers/GaudiExecRTHandlers.py", line 170, in prepareCommand
WARNING      with open(app.directory+'/Makefile', "r") as makefile:
WARNING  FileNotFoundError: [Errno 2] No such file or directory: '/tmp/masmith/DaVinciDev_v45r7/Makefile'
WARNING  --------------------------------------------------
ERROR    [Errno 2] No such file or directory: '/tmp/masmith/DaVinciDev_v45r7/Makefile' ... reverting job 56 to the new status
INFO     job 56 status changed to "new"
ERROR    JobError: Error: [Errno 2] No such file or directory: '/tmp/masmith/DaVinciDev_v45r7/Makefile'

```

**Comment by mesmith75** [comment]
Turns out this is just a quirk of GaudiExec. It will be fixed in #1891
