### ISSUE TITLE
Ganga complaining about 'setCondorDateFormat' is not defined

### ISSUE THREAD

**Issue by asnaylor** [ganga-devs/ganga#1936]
Ran a ganga job with the condor backend, ganga submitted it to the HTCondor cluster but kept complaining in an infinite loop when ganga was open that `setCondorDateFormat` is not defined:
```
WARNING  ---------- error in user/extension code ----------
WARNING  Traceback (most recent call last):
WARNING    File "/home/anaylor/.pyenv/versions/miniconda3-4.3.30/lib/python3.6/site-packages/ganga/GangaCore/GPIDev/Lib/Job/Job.py", line 599, in updateStatus
WARNING      self.time.timenow(newstatus)
WARNING    File "/home/anaylor/.pyenv/versions/miniconda3-4.3.30/lib/python3.6/site-packages/ganga/GangaCore/GPIDev/Lib/Job/JobTime.py", line 127, in
timenow
WARNING      be_statetime = stripProxy(j.backend).getStateTime(childstatus)
WARNING    File "/home/anaylor/.pyenv/versions/miniconda3-4.3.30/lib/python3.6/site-packages/ganga/GangaCore/Lib/Condor/Condor.py", line 762, in getSt
ateTime
WARNING      setCondorDateFormat(splitLine[2])
WARNING  NameError: name 'setCondorDateFormat' is not defined
WARNING  --------------------------------------------------
ERROR    JobStatusError: name 'setCondorDateFormat' is not defined
```

**Comment by egede** [comment]
Hi. Which version of `ganga` do you use? I can't quite get the line numbers to match with what I see in the source. Please provide a minimally failing example in the latest version.

**Comment by asnaylor** [comment]
I was using ganga version 8.3.5 but this bug must have been fixed in subsequent versions as when I updated to the latest 8.5.0 I'm getting no issues now. 👍🏻
