### ISSUE TITLE
[Dev] Autocomplete for shell commands related to file paths results in errors on Centos7

### ISSUE THREAD

**Issue by laurentdufour** [ganga-devs/ganga#2225]
When running Ganga 8.6.0 DEV on a centos7 machine, typing `ls ~/[tab]` for example results in various errors about the Python grammar:

```
Traceback (most recent call last):
  File "/cvmfs/ganga.cern.ch/Ganga/install/DEV/miniconda3/lib/python3.11/site-packages/jedi/cache.py", line 109, in wrapper
    return dct[key]
           ~~~^^^^^
KeyError: ((), frozenset())

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/cvmfs/ganga.cern.ch/Ganga/install/DEV/miniconda3/lib/python3.11/site-packages/parso/grammar.py", line 246, in load_grammar
    return _loaded_grammars[path]
           ~~~~~~~~~~~~~~~~^^^^^^
KeyError: '/cvmfs/ganga.cern.ch/Ganga/install/DEV/miniconda3/lib/python3.11/site-packages/parso/python/grammar311.txt'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/cvmfs/ganga.cern.ch/Ganga/install/DEV/miniconda3/lib/python3.11/site-packages/parso/grammar.py", line 249, in load_grammar
    with open(path) as f:
         ^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: '/cvmfs/ganga.cern.ch/Ganga/install/DEV/miniconda3/lib/python3.11/site-packages/parso/python/grammar311.txt'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/cvmfs/ganga.cern.ch/Ganga/install/DEV/miniconda3/lib/python3.11/site-packages/IPython/core/completer.py", line 3171, in _complete
    result = matcher(context)
             ^^^^^^^^^^^^^^^^
  File "/cvmfs/ganga.cern.ch/Ganga/install/DEV/miniconda3/lib/python3.11/site-packages/IPython/core/completer.py", line 2224, in _jedi_matcher
    matches = self._jedi_matches(
              ^^^^^^^^^^^^^^^^^^^
  File "/cvmfs/ganga.cern.ch/Ganga/install/DEV/miniconda3/lib/python3.11/site-packages/IPython/core/completer.py", line 2278, in _jedi_matches
    interpreter = jedi.Interpreter(text[:offset], namespaces)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/cvmfs/ganga.cern.ch/Ganga/install/DEV/miniconda3/lib/python3.11/site-packages/jedi/api/__init__.py", line 858, in __init__
    super(Interpreter, self).__init__(code, environment=environment,
  File "/cvmfs/ganga.cern.ch/Ganga/install/DEV/miniconda3/lib/python3.11/site-packages/jedi/api/__init__.py", line 184, in __init__
    self._inference_state = InferenceState(
                            ^^^^^^^^^^^^^^^
  File "/cvmfs/ganga.cern.ch/Ganga/install/DEV/miniconda3/lib/python3.11/site-packages/jedi/inference/__init__.py", line 91, in __init__
    self.grammar = environment.get_grammar()
                   ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/cvmfs/ganga.cern.ch/Ganga/install/DEV/miniconda3/lib/python3.11/site-packages/jedi/cache.py", line 111, in wrapper
    result = method(self, *args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/cvmfs/ganga.cern.ch/Ganga/install/DEV/miniconda3/lib/python3.11/site-packages/jedi/api/environment.py", line 37, in get_grammar
    return parso.load_grammar(version=version_string)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/cvmfs/ganga.cern.ch/Ganga/install/DEV/miniconda3/lib/python3.11/site-packages/parso/grammar.py", line 260, in load_grammar
    return load_grammar(**kwargs)
```

Despite these errors, ganga keeps on running fine.

**Comment by mesmith75** [comment]
Thanks - it looks like the default version of parso (and jedi) was too old. I'll update them.
