### ISSUE TITLE
Considering support for linux kernel keyring in AfsToken

### ISSUE THREAD

**Issue by laf070810** [ganga-devs/ganga#2230]
Recently, CERN lxplus service has switched from CC 7 resources to EL 9 resources (see <https://cern.service-now.com/service-portal?id=outage&n=OTG0076556>), resulting in Kerberos tickets being stored in kernel keyring rather than in a file (see <https://cern.service-now.com/service-portal?id=kb_article&n=KB0009147>). Opening ganga on lxplus will yield the following error and immediately exit

```
Traceback (most recent call last):
  File "/cvmfs/ganga.cern.ch/Ganga/install/LATEST/bin/ganga", line 97, in <module>
    GangaCore.Runtime.setupGanga()
  File "/cvmfs/ganga.cern.ch/Ganga/install/8.6.8/lib/python3.8/site-packages/ganga/GangaCore/Runtime/__init__.py", line 19, in setupGanga
    GangaCore.Runtime._prog.bootstrap(GangaCore.Runtime._prog.interactive)
  File "/cvmfs/ganga.cern.ch/Ganga/install/8.6.8/lib/python3.8/site-packages/ganga/GangaCore/Runtime/bootstrap.py", line 936, in bootstrap
    credential_store.create(AfsToken(), create=False, check_file=True)
  File "/cvmfs/ganga.cern.ch/Ganga/install/8.6.8/lib/python3.8/site-packages/ganga/GangaCore/GPIDev/Credentials/CredentialStore.py", line 94, in create
    cred = query.info_class(query, check_file=check_file, create=create)
  File "/cvmfs/ganga.cern.ch/Ganga/install/8.6.8/lib/python3.8/site-packages/ganga/GangaCore/GPIDev/Credentials/AfsToken.py", line 44, in __init__
    super(AfsTokenInfo, self).__init__(requirements, check_file, create)
  File "/cvmfs/ganga.cern.ch/Ganga/install/8.6.8/lib/python3.8/site-packages/ganga/GangaCore/GPIDev/Adapters/ICredentialInfo.py", line 130, in __init__
    raise IOError('Proxy file {path} not found'.format(path=self.location))
OSError: Proxy file /tmp/krb5cc_137550 not found
INFO     Stopping Job processing before shutting down Repositories
INFO     Shutting Down Ganga Repositories
INFO     Registry Shutdown
```

It seems that the cause is that AfsToken in ganga only recognizes file-based Kerberos tickets (see <https://github.com/ganga-devs/ganga/blob/develop/ganga/GangaCore/GPIDev/Credentials/AfsToken.py#L147>). A workaround is to `export KRB5CCNAME=${XDG_RUNTIME_DIR}/krb5cc` before using ganga, which recovers the normal use but credential_store.renew() is still broken

```
Ganga In [1]: credential_store.renew()
ERROR    !!Unknown/Unexpected ERROR!!
ERROR    If you're able to reproduce this please report this to the Ganga developers!
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
Cell In[1], line 1
----> 1 credential_store.renew()

File /cvmfs/ganga.cern.ch/Ganga/install/8.6.8/lib/python3.8/site-packages/ganga/GangaCore/GPIDev/Base/Proxy.py:734, in proxy_wrap.<locals>.proxy_wrapped(*args, **kwargs)
    732 s_kwargs = dict((name, stripProxy(a)) for name, a in kwargs.items())
    733 try:
--> 734     r = f(*s_args, **s_kwargs)
    735 except KeyboardInterrupt:
    736     logger.error("Command was interrupted by a Ctrl+C event!")

File /cvmfs/ganga.cern.ch/Ganga/install/8.6.8/lib/python3.8/site-packages/ganga/GangaCore/GPIDev/Credentials/CredentialStore.py:313, in CredentialStore.renew(self)
    307 """
    308 Renew all credentials which are invalid or will expire soon.
    309 It also uses the entries in `needed_credentials` and adds and renews those
    310 TODO Should this function be standalone?
    311 """
    312 for cred in self.credentials:
--> 313     if not cred.is_valid() or cred.time_left() < timedelta(hours=1):
    314         cred.renew()
    315 for cred_req in needed_credentials - self.credentials:

File /cvmfs/ganga.cern.ch/Ganga/install/8.6.8/lib/python3.8/site-packages/ganga/GangaCore/GPIDev/Adapters/ICredentialInfo.py:194, in ICredentialInfo.is_valid(self)
    190 """
    191 Is the credential valid to be used
    192 """
    193 # TODO We should check that there's more than some minimum time left on the proxy
--> 194 return self.time_left() > timedelta()

File /cvmfs/ganga.cern.ch/Ganga/install/8.6.8/lib/python3.8/site-packages/ganga/GangaCore/GPIDev/Adapters/ICredentialInfo.py:209, in ICredentialInfo.time_left(self)
    204 def time_left(self):
    205     # type: () -> datetime.timedelta
    206     """
    207     Returns the time left
    208     """
--> 209     time_left = self.expiry_time() - datetime.now()
    210     return max(time_left, timedelta())

TypeError: unsupported operand type(s) for -: 'NoneType' and 'datetime.datetime'
```

Would it be possible to add support for linux kernel keyring in ganga?

**Comment by mesmith75** [comment]
This has been fixed in https://github.com/ganga-devs/ganga/pull/2223.
Ultimately there will be a more comprehensive rewrite as mentioned in https://github.com/ganga-devs/ganga/issues/2103
Note that we cannot explicitly use the keyring as we want Ganga to still work with centos7

**Comment by laf070810** [comment]
Thank you very much for your clarification. Sorry that I did not check the past issues carefully. This means that for now we can use `ganga --ganga-version DEV` to open the DEV version of ganga to avoid the problem, right? Hope that the next production release will be coming soon :)
