### ISSUE TITLE
Error with OfflineGangaDiracSplitter

### ISSUE THREAD

**Issue by mesmith75** [ganga-devs/ganga#2231]
I assume it is a consequence of the new python
```python
INFO     Calculating best data subsets
WARNING  ---------- error in user/extension code ----------
WARNING  Traceback (most recent call last):
WARNING    File "/cvmfs/ganga.cern.ch/Ganga/install/DEV/miniconda3/lib/python3.11/site-packages/ganga/GangaCore/GPIDev/Lib/Job/Job.py", line 2028, in submit
WARNING      rjobs = self._doSplitting()
WARNING              ^^^^^^^^^^^^^^^^^^^
WARNING    File "/cvmfs/ganga.cern.ch/Ganga/install/DEV/miniconda3/lib/python3.11/site-packages/ganga/GangaCore/GPIDev/Lib/Job/Job.py", line 1782, in _doSplitting
WARNING      subjobs = self.splitter.validatedSplit(self)
WARNING                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
WARNING    File "/cvmfs/ganga.cern.ch/Ganga/install/DEV/miniconda3/lib/python3.11/site-packages/ganga/GangaCore/GPIDev/Adapters/ISplitter.py", line 69, in validatedSplit
WARNING      subjobs = self.split(stripProxy(job))
WARNING                ^^^^^^^^^^^^^^^^^^^^^^^^^^^
WARNING    File "/cvmfs/ganga.cern.ch/Ganga/install/DEV/miniconda3/lib/python3.11/site-packages/ganga/GangaLHCb/Lib/Splitters/SplitByFiles.py", line 242, in split
WARNING      split_return = super(SplitByFiles, self).split(job)
WARNING                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
WARNING    File "/cvmfs/ganga.cern.ch/Ganga/install/DEV/miniconda3/lib/python3.11/site-packages/ganga/GangaGaudi/Lib/Splitters/GaudiInputDataSplitter.py", line 71, in split
WARNING      for dataset in all_jobs:
WARNING    File "/cvmfs/ganga.cern.ch/Ganga/install/DEV/miniconda3/lib/python3.11/site-packages/ganga/GangaDirac/Lib/Splitters/OfflineGangaDiracSplitter.py", line 478, in OfflineGangaDiracSplitter
WARNING      allSubSets = performSplitting(site_dict, filesPerJob, allChosenSets, wanted_common_site,
WARNING                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
WARNING    File "/cvmfs/ganga.cern.ch/Ganga/install/DEV/miniconda3/lib/python3.11/site-packages/ganga/GangaDirac/Lib/Splitters/OfflineGangaDiracSplitter.py", line 585, in performSplitting
WARNING      allChosenSets[iterating_LFN] = generate_site_selection(
WARNING                                     ^^^^^^^^^^^^^^^^^^^^^^^^
WARNING    File "/cvmfs/ganga.cern.ch/Ganga/install/DEV/miniconda3/lib/python3.11/site-packages/ganga/GangaDirac/Lib/Splitters/OfflineGangaDiracSplitter.py", line 202, in generate_site_selection
WARNING      this_SE = find_random_site(input_site, used_SE)
WARNING                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
WARNING    File "/cvmfs/ganga.cern.ch/Ganga/install/DEV/miniconda3/lib/python3.11/site-packages/ganga/GangaDirac/Lib/Splitters/OfflineGangaDiracSplitter.py", line 135, in find_random_site
WARNING      this_element = global_random.sample(input_list, 1)[0]
WARNING                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
WARNING    File "/cvmfs/ganga.cern.ch/Ganga/install/DEV/miniconda3/lib/python3.11/random.py", line 439, in sample
WARNING      raise TypeError("Population must be a sequence.  "
WARNING  TypeError: Population must be a sequence.  For dicts or sets, use sorted(d).
WARNING  --------------------------------------------------
ERROR    Population must be a sequence.  For dicts or sets, use sorted(d). ... reverting job 2543 to the new status
INFO     job 2543 status changed to "new"

```

**Comment by mesmith75** [comment]
Closed by #2260
