### ISSUE TITLE
Problems to acess ganga on lxplus9

### ISSUE THREAD

**Issue by LeonSantoro** [ganga-devs/ganga#2232]
Yesterday i try to acess ganga to get my output files for a finished jobs. But, for some reason. since yesterday I can only loggin on lxplus9 machines. Machins running Red Hat Linux 9. And for some reason, in this machines ganga dont initiallize. I was before running ganga on cent os 7. How I fix this problens ? 

The error obtained are : 

*** Welcome to Ganga ***
Version: 8.6.8
Documentation: https://ganga.readthedocs.io/en/latest/
Report issues: https://github.com/ganga-devs/ganga
Type help() or help('index') for online help.

This is free software (GPL), and you are welcome to redistribute it
under certain conditions; type license() for details.

INFO     reading config file /afs/cern.ch/user/l/lesantor/.gangarc
INFO     reading config file /cvmfs/ganga.cern.ch/Ganga/install/8.6.8/lib/python3.8/site-packages/ganga/GangaLHCb/LHCb.ini
INFO     reading config file /cvmfs/lhcb.cern.ch/lib/GangaConfig/config/8-0-0/GangaLHCb.ini
INFO     Using LHCbDirac version prod
Traceback (most recent call last):
  File "/cvmfs/ganga.cern.ch/Ganga/install/LATEST/bin/ganga", line 97, in <module>
    GangaCore.Runtime.setupGanga()
  File "/cvmfs/ganga.cern.ch/Ganga/install/8.6.8/lib/python3.8/site-packages/ganga/GangaCore/Runtime/__init__.py", line 19, in setupGanga
    GangaCore.Runtime._prog.bootstrap(GangaCore.Runtime._prog.interactive)
  File "/cvmfs/ganga.cern.ch/Ganga/install/8.6.8/lib/python3.8/site-packages/ganga/GangaCore/Runtime/bootstrap.py", line 936, in bootstrap
    credential_store.create(AfsToken(), create=False, check_file=True)
  File "/cvmfs/ganga.cern.ch/Ganga/install/8.6.8/lib/python3.8/site-packages/ganga/GangaCore/GPIDev/Credentials/CredentialStore.py", line 94, in create
    cred = query.info_class(query, check_file=check_file, create=create)
  File "/cvmfs/ganga.cern.ch/Ganga/install/8.6.8/lib/python3.8/site-packages/ganga/GangaCore/GPIDev/Credentials/AfsToken.py", line 44, in __init__
    super(AfsTokenInfo, self).__init__(requirements, check_file, create)
  File "/cvmfs/ganga.cern.ch/Ganga/install/8.6.8/lib/python3.8/site-packages/ganga/GangaCore/GPIDev/Adapters/ICredentialInfo.py", line 130, in __init__
    raise IOError('Proxy file {path} not found'.format(path=self.location))
OSError: Proxy file /tmp/krb5cc_136376 not found
INFO     Stopping Job processing before shutting down Repositories
INFO     Shutting Down Ganga Repositories
INFO     Registry Shutdown

**Comment by egede** [comment]
This is fixed by #2223 but waiting for the release to be done. Please use Ganga on `lxplus7` until release comes out.
