### ISSUE TITLE
Improve sandbox exceptions

### ISSUE THREAD

**Issue by mesmith75** [ganga-devs/ganga#2258]
The exceptions for missing sandboxes have gotten more verbose:
```python
[19:26:03]
Ganga In [1]: ERROR    Task exception was never retrieved
future: <Task finished name='Task-24' coro=<DiracBase.job_finalisation() done, defined at /cvmfs/ganga.cern.ch/Ganga/install/8.7.0/lib/python3.11/site-packages/ganga/GangaDirac/Lib/Backends/DiracBase.py:1287> exception=GangaDiracError(GangaDiracError('No Output sandbox found for job 831910823. Possible causes are: the job does not exist, no sandbox was registered or you do not have permission to access it.'))>
Traceback (most recent call last):
  File "/cvmfs/ganga.cern.ch/Ganga/install/8.7.0/lib/python3.11/site-packages/ganga/GangaDirac/Lib/Server/DiracProcessManager.py", line 109, in execute
    returnable = self.parse_command_result(dirac_result, return_raw_dict, env_hash)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/cvmfs/ganga.cern.ch/Ganga/install/8.7.0/lib/python3.11/site-packages/ganga/GangaDirac/Lib/Server/DiracProcessManager.py", line 81, in parse_command_result
    raise GangaDiracError(result['Message'])
GangaDirac.Lib.Utilities.DiracUtilities.GangaDiracError: GangaDiracError: No Output sandbox found for job 831910823. Possible causes are: the job does not exist, no sandbox was registered or you do not have permission to access it.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/cvmfs/ganga.cern.ch/Ganga/install/8.7.0/lib/python3.11/site-packages/ganga/GangaDirac/Lib/Backends/DiracBase.py", line 1315, in job_finalisation
    await task
  File "/cvmfs/ganga.cern.ch/Ganga/install/8.7.0/lib/python3.11/site-packages/ganga/GangaDirac/Lib/Backends/DiracBase.py", line 1100, in _internal_job_finalisation
    await DiracBase.finalise_failed_job(job)
  File "/cvmfs/ganga.cern.ch/Ganga/install/8.7.0/lib/python3.11/site-packages/ganga/GangaDirac/Lib/Backends/DiracBase.py", line 1120, in finalise_failed_job
    await dm.execute(getOutputSandbox, args_dict={
  File "/cvmfs/ganga.cern.ch/Ganga/install/8.7.0/lib/python3.11/site-packages/ganga/GangaDirac/Lib/Server/DiracProcessManager.py", line 118, in execute
    raise GangaDiracError(err)
GangaDirac.Lib.Utilities.DiracUtilities.GangaDiracError: GangaDiracError: GangaDiracError: No Output sandbox found for job 831910823. Possible causes are: the job does not exist, no sandbox was registered or you do not have permission to access it.
ERROR    Task exception was never retrieved
future: <Task finished name='Task-25' coro=<DiracBase.job_finalisation() done, defined at /cvmfs/ganga.cern.ch/Ganga/install/8.7.0/lib/python3.11/site-packages/ganga/GangaDirac/Lib/Backends/DiracBase.py:1287> exception=GangaDiracError(GangaDiracError('No Output sandbox found for job 832242783. Possible causes are: the job does not exist, no sandbox was registered or you do not have permission to access it.'))>
Traceback (most recent call last):
  File "/cvmfs/ganga.cern.ch/Ganga/install/8.7.0/lib/python3.11/site-packages/ganga/GangaDirac/Lib/Server/DiracProcessManager.py", line 109, in execute
    returnable = self.parse_command_result(dirac_result, return_raw_dict, env_hash)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/cvmfs/ganga.cern.ch/Ganga/install/8.7.0/lib/python3.11/site-packages/ganga/GangaDirac/Lib/Server/DiracProcessManager.py", line 81, in parse_command_result
    raise GangaDiracError(result['Message'])
GangaDirac.Lib.Utilities.DiracUtilities.GangaDiracError: GangaDiracError: No Output sandbox found for job 832242783. Possible causes are: the job does not exist, no sandbox was registered or you do not have permission to access it.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/cvmfs/ganga.cern.ch/Ganga/install/8.7.0/lib/python3.11/site-packages/ganga/GangaDirac/Lib/Backends/DiracBase.py", line 1315, in job_finalisation
    await task
  File "/cvmfs/ganga.cern.ch/Ganga/install/8.7.0/lib/python3.11/site-packages/ganga/GangaDirac/Lib/Backends/DiracBase.py", line 1100, in _internal_job_finalisation
    await DiracBase.finalise_failed_job(job)
  File "/cvmfs/ganga.cern.ch/Ganga/install/8.7.0/lib/python3.11/site-packages/ganga/GangaDirac/Lib/Backends/DiracBase.py", line 1120, in finalise_failed_job
    await dm.execute(getOutputSandbox, args_dict={
  File "/cvmfs/ganga.cern.ch/Ganga/install/8.7.0/lib/python3.11/site-packages/ganga/GangaDirac/Lib/Server/DiracProcessManager.py", line 118, in execute
    raise GangaDiracError(err)
[19:26:03]
Ganga In [1]: 

```
The `GangaDiracError` is fine but it would be nice to fix that `Task exception was never retrieved`

**Comment by joj0s** [comment]
I'll look into it, should be just a matter of adding a handler. Can you suggest a way to reproduce this exception reliably?

**Comment by mesmith75** [comment]
I think it is any Dirac command that is not successful - so something that raises an exception in its execute. You can just modify a basic Dirac function to always raise an exception.
