### ISSUE TITLE
Condor doesn't work on el9

### ISSUE THREAD

**Issue by mesmith75** [ganga-devs/ganga#2262]
```python
WARNING  ---------- error in user/extension code ----------
WARNING  Traceback (most recent call last):
WARNING    File "/cvmfs/ganga.cern.ch/Ganga/install/8.7.0/lib/python3.11/site-packages/ganga/GangaCore/GPIDev/Lib/Job/Job.py", line 2084, in submit
WARNING      r = self.backend.master_submit(
WARNING          ^^^^^^^^^^^^^^^^^^^^^^^^^^^
WARNING    File "/cvmfs/ganga.cern.ch/Ganga/install/8.7.0/lib/python3.11/site-packages/ganga/GangaCore/Lib/Condor/Condor.py", line 124, in master_submit
WARNING      credd.add_user_cred(htcondor.CredTypes.Kerberos, None)
WARNING    File "/cvmfs/ganga.cern.ch/Ganga/install/8.7.0/lib/python3.11/site-packages/htcondor/_lock.py", line 70, in wrapper
WARNING      rv = func(*args, **kwargs)
WARNING           ^^^^^^^^^^^^^^^^^^^^^
WARNING  htcondor.HTCondorIOError: Communication error
WARNING  --------------------------------------------------
ERROR    Communication error ... reverting job 388 to the new status
```
The error seems to be with our version of the condor package - I wonder if we can really have it for both centos7 and el9 as it is compiled?

**Comment by mesmith75** [comment]
This is further complicated by our not having a choice of os for our `/cvmfs` machine. The simplest solution is to go back to using the command line utilities

**Comment by mesmith75** [comment]
I think ultimately this is something we will have to live with. Our `/cvmfs` machine will be upgrade in the next few months - then condor submission won't work with centos7.
