### ISSUE TITLE
Exception when starting ganga version 8.7.9

### ISSUE THREAD

**Issue by heistera** [ganga-devs/ganga#2375]
The start of ganga shown below does not look healthy to me. Here is the output:

[heister@lxbatch01.physik.rwth-aachen.de][~/gangadir]% ganga

*** Welcome to Ganga ***
Version: 8.7.9
Documentation: https://ganga.readthedocs.io/en/latest/
Report issues: https://github.com/ganga-devs/ganga
Type help() or help('index') for online help.

This is free software (GPL), and you are welcome to redistribute it
under certain conditions; type license() for details.

INFO     reading config file /home/home3/gast/heister/.gangarc
INFO     reading config file /cvmfs/ganga.cern.ch/Ganga/install/8.7.9/lib/python3.11/site-packages/ganga/GangaLHCb/LHCb.ini
INFO     reading config file /cvmfs/lhcb.cern.ch/lib/GangaConfig/config/8-0-0/GangaLHCb.ini
INFO     Using LHCbDirac version prod
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/cvmfs/ganga.cern.ch/Ganga/install/micromamba_el9/lib/python3.11/threading.py", line 1045, in _bootstrap_inner
    self.run()
  File "/cvmfs/ganga.cern.ch/Ganga/install/8.7.9/lib/python3.11/site-packages/ganga/GangaCore/Utility/stacktracer.py", line 96, in run
    self.stacktraces()
  File "/cvmfs/ganga.cern.ch/Ganga/install/8.7.9/lib/python3.11/site-packages/ganga/GangaCore/Utility/stacktracer.py", line 109, in stacktraces
    fout.write(stacktraces())
               ^^^^^^^^^^^^^
  File "/cvmfs/ganga.cern.ch/Ganga/install/8.7.9/lib/python3.11/site-packages/ganga/GangaCore/Utility/stacktracer.py", line 56, in stacktraces
    trace = traceback.format_stack(stack)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/cvmfs/ganga.cern.ch/Ganga/install/micromamba_el9/lib/python3.11/traceback.py", line 214, in format_stack
    return format_list(extract_stack(f, limit=limit))
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/cvmfs/ganga.cern.ch/Ganga/install/micromamba_el9/lib/python3.11/traceback.py", line 228, in extract_stack
    stack = StackSummary.extract(walk_stack(f), limit=limit)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/cvmfs/ganga.cern.ch/Ganga/install/micromamba_el9/lib/python3.11/traceback.py", line 390, in extract
    return klass._extract_from_extended_frame_gen(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/cvmfs/ganga.cern.ch/Ganga/install/micromamba_el9/lib/python3.11/traceback.py", line 413, in _extract_from_extended_frame_gen
    for f, (lineno, end_lineno, colno, end_colno) in frame_gen:
  File "/cvmfs/ganga.cern.ch/Ganga/install/micromamba_el9/lib/python3.11/traceback.py", line 387, in extended_frame_gen
    for f, lineno in frame_gen:
  File "/cvmfs/ganga.cern.ch/Ganga/install/micromamba_el9/lib/python3.11/traceback.py", line 331, in walk_stack
    yield f, f.f_lineno
             ^^^^^^^^^^
AttributeError: 'dict' object has no attribute 'f_lineno'

 === Welcome to Ganga on CVMFS. In case of problems contact lhcb-distributed-analysis@cern.ch === 

[17:12:31]
Ganga In [1]:

**Comment by mesmith75** [comment]
How exactly are you managing to produce this? It works perfectly fine on lxplus and the Imperial group machines.  With no extra information there is nothing we can do. There must be something in your local environment. Are you starting Ganga in a totally clean shell?
![image](https://github.com/user-attachments/assets/a8e6de81-0925-4d62-976a-27dda8da1b95)

**Comment by heistera** [comment]
I've just started ganga. Ganga then processed 11 jobs with > 1000 sub jobs before starting ... nothing else ...

**Comment by egede** [comment]
It is a bit odd to start ganga from within the gangadir, but I do not think it should matter. 

Otherwise, my suspicion is also that you have something in the environment that upsets ganga.

**Comment by heistera** [comment]
I did not change anything in my environment for some time. I am controlling all relevant scripts with git. Since my report it never happened again.
