### ISSUE TITLE
Exceptions thrown from threads on shutdown with Python 2.6 and Python 2.7

### ISSUE THREAD

**Issue by egede** [ganga-devs/ganga#285]
Working on the 6.1.17 release candidate, I see the errors below, each time I exit when using Python 2.6. With Python 2.7 there are no exceptions.

```
[20:15:07]
Ganga In [9]: 
Do you really want to exit ([y]/n)? 

Ganga.Core.MonitoringComponent     : INFO     Some tasks are still running on Monitoring Loop
Ganga.Core.MonitoringComponent     : INFO     Please wait for them to finish to avoid data corruption
Ganga.Core.InternalServices        : INFO     Stopping Job processing before shutting down Repositories
Ganga.Core.InternalServices        : INFO     Shutting Down Ganga Repositories
Ganga.Runtime                      : INFO     Registry Shutdown
Exception in thread GANGA_Update_Thread_Ganga_Worker_0 (most likely raised during interpreter shutdown):
Traceback (most recent call last):
  File "/usr/lib64/python2.6/threading.py", line 532, in __bootstrap_inner
  File "/usr/lib64/python2.6/threading.py", line 484, in run
  File "/home/egede/Ganga/install/ganga/python/Ganga/Core/GangaThread/WorkerThreads/WorkerThreadPool.py", line 78, in __worker_thread
  File "/usr/lib64/python2.6/Queue.py", line 177, in get
  File "/usr/lib64/python2.6/threading.py", line 254, in wait
<type 'exceptions.TypeError'>: 'NoneType' object is not callable
Exception in thread GANGA_Update_Thread_Ganga_Worker_1 (most likely raised during interpreter shutdown):
Traceback (most recent call last):
  File "/usr/lib64/python2.6/threading.py", line 532, in __bootstrap_inner
  File "/usr/lib64/python2.6/threading.py", line 484, in run
  File "/home/egede/Ganga/install/ganga/python/Ganga/Core/GangaThread/WorkerThreads/WorkerThreadPool.py", line 78, in __worker_thread
  File "/usr/lib64/python2.6/Queue.py", line 177, in get
  File "/usr/lib64/python2.6/threading.py", line 254, in wait
<type 'exceptions.TypeError'>: 'NoneType' object is not callable
Exception in thread GANGA_Update_Thread_Ganga_Worker_2 (most likely raised during interpreter shutdown):
Traceback (most recent call last):
  File "/usr/lib64/python2.6/threading.py", line 532, in __bootstrap_inner
  File "/usr/lib64/python2.6/threading.py", line 484, in run
  File "/home/egede/Ganga/install/ganga/python/Ganga/Core/GangaThread/WorkerThreads/WorkerThreadPool.py", line 78, in __worker_thread
  File "/usr/lib64/python2.6/Queue.py", line 177, in get
  File "/usr/lib64/python2.6/threading.py", line 254, in wait
<type 'exceptions.TypeError'>: 'NoneType' object is not callable
Exception in thread GANGA_Update_Thread_User_Worker_1 (most likely raised during interpreter shutdown):
Traceback (most recent call last):
  File "/usr/lib64/python2.6/threading.py", line 532, in __bootstrap_inner
  File "/usr/lib64/python2.6/threading.py", line 484, in run
  File "/home/egede/Ganga/install/ganga/python/Ganga/Core/GangaThread/WorkerThreads/WorkerThreadPool.py", line 78, in __worker_thread
  File "/usr/lib64/python2.6/Queue.py", line 177, in get
  File "/usr/lib64/python2.6/threading.py", line 254, in wait
<type 'exceptions.TypeError'>: 'NoneType' object is not callable
Exception in thread GANGA_Update_Thread_User_Worker_0 (most likely raised during interpreter shutdown):
Traceback (most recent call last):
  File "/usr/lib64/python2.6/threading.py", line 532, in __bootstrap_inner
  File "/usr/lib64/python2.6/threading.py", line 484, in run
  File "/home/egede/Ganga/install/ganga/python/Ganga/Core/GangaThread/WorkerThreads/WorkerThreadPool.py", line 78, in __worker_thread
  File "/usr/lib64/python2.6/Queue.py", line 177, in get
  File "/usr/lib64/python2.6/threading.py", line 254, in wait
<type 'exceptions.TypeError'>: 'NoneType' object is not callable
Exception in thread GANGA_Update_Thread_User_Worker_2 (most likely raised during interpreter shutdown):
Traceback (most recent call last):
  File "/usr/lib64/python2.6/threading.py", line 532, in __bootstrap_inner
  File "/usr/lib64/python2.6/threading.py", line 484, in run
  File "/home/egede/Ganga/install/ganga/python/Ganga/Core/GangaThread/WorkerThreads/WorkerThreadPool.py", line 78, in __worker_thread
  File "/usr/lib64/python2.6/Queue.py", line 177, in get
  File "/usr/lib64/python2.6/threading.py", line 254, in wait
<type 'exceptions.TypeError'>: 'NoneType' object is not callable
```

**Comment by rob-c** [comment]
I've seen this before and tbh I'm inclined to believe we're doing something bad with daemon threads.
https://github.com/ganga-devs/ganga/blob/develop/python/Ganga/Core/GangaThread/WorkerThreads/WorkerThreadPool.py#L78
The line referenced above has a call only to an internal method which shouldn't throw this error.

Given the threads largely always exit here I'd propose to add an exception to handle it gracefully as Python 2.7 tries to (I think).

That or we need to think about how we're stopping and shutting the queues system again. I'm very happy for someone to take a look and see if there is anything I've missed there.

**Comment by egede** [comment]
I am afraid that I just saw the same error when going through the shutdown in Python 2.7

```
Ganga In [16]: 
Do you really want to exit ([y]/n)? 

Ganga.Core.InternalServices        : INFO     Stopping Job processing before shutting down Repositories
Ganga.Core.InternalServices        : INFO     Shutting Down Ganga Repositories
Ganga.Runtime                      : INFO     Registry Shutdown
Exception in thread GANGA_Update_Thread_Ganga_Worker_0 (most likely raised during interpreter shutdown):
Traceback (most recent call last):
  File "/cvmfs/sft.cern.ch/lcg/external/Python/2.7.4/x86_64-slc6-gcc48-opt/lib/python2.7/threading.py", line 810, in __bootstrap_inner
  File "/cvmfs/sft.cern.ch/lcg/external/Python/2.7.4/x86_64-slc6-gcc48-opt/lib/python2.7/threading.py", line 763, in run
  File "/home/egede/Ganga/install/ganga/python/Ganga/Core/GangaThread/WorkerThreads/WorkerThreadPool.py", line 78, in __worker_thread
  File "/cvmfs/sft.cern.ch/lcg/external/Python/2.7.4/x86_64-slc6-gcc48-opt/lib/python2.7/Queue.py", line 177, in get
  File "/cvmfs/sft.cern.ch/lcg/external/Python/2.7.4/x86_64-slc6-gcc48-opt/lib/python2.7/threading.py", line 354, in wait
<type 'exceptions.TypeError'>: 'NoneType' object is not callable
Exception in thread GANGA_Update_Thread_User_Worker_1 (most likely raised during interpreter shutdown):
Traceback (most recent call last):
  File "/cvmfs/sft.cern.ch/lcg/external/Python/2.7.4/x86_64-slc6-gcc48-opt/lib/python2.7/threading.py", line 810, in __bootstrap_inner
  File "/cvmfs/sft.cern.ch/lcg/external/Python/2.7.4/x86_64-slc6-gcc48-opt/lib/python2.7/threading.py", line 763, in run
  File "/home/egede/Ganga/install/ganga/python/Ganga/Core/GangaThread/WorkerThreads/WorkerThreadPool.py", line 78, in __worker_thread
  File "/cvmfs/sft.cern.ch/lcg/external/Python/2.7.4/x86_64-slc6-gcc48-opt/lib/python2.7/Queue.py", line 177, in get
  File "/cvmfs/sft.cern.ch/lcg/external/Python/2.7.4/x86_64-slc6-gcc48-opt/lib/python2.7/threading.py", line 354, in wait
<type 'exceptions.TypeError'>: 'NoneType' object is not callable
Exception in thread GANGA_Update_Thread_User_Worker_2 (most likely raised during interpreter shutdown):
Traceback (most recent call last):
  File "/cvmfs/sft.cern.ch/lcg/external/Python/2.7.4/x86_64-slc6-gcc48-opt/lib/python2.7/threading.py", line 810, in __bootstrap_inner
  File "/cvmfs/sft.cern.ch/lcg/external/Python/2.7.4/x86_64-slc6-gcc48-opt/lib/python2.7/threading.py", line 763, in run
  File "/home/egede/Ganga/install/ganga/python/Ganga/Core/GangaThread/WorkerThreads/WorkerThreadPool.py", line 78, in __worker_thread
  File "/cvmfs/sft.cern.ch/lcg/external/Python/2.7.4/x86_64-slc6-gcc48-opt/lib/python2.7/Queue.py", line 177, in get
  File "/cvmfs/sft.cern.ch/lcg/external/Python/2.7.4/x86_64-slc6-gcc48-opt/lib/python2.7/threading.py", line 354, in wait
<type 'exceptions.TypeError'>: 'NoneType' object is not callable
Exception in thread GANGA_Update_Thread_User_Worker_0 (most likely raised during interpreter shutdown):
Traceback (most recent call last):
  File "/cvmfs/sft.cern.ch/lcg/external/Python/2.7.4/x86_64-slc6-gcc48-opt/lib/python2.7/threading.py", line 810, in __bootstrap_inner
  File "/cvmfs/sft.cern.ch/lcg/external/Python/2.7.4/x86_64-slc6-gcc48-opt/lib/python2.7/threading.py", line 763, in run
  File "/home/egede/Ganga/install/ganga/python/Ganga/Core/GangaThread/WorkerThreads/WorkerThreadPool.py", line 78, in __worker_thread
  File "/cvmfs/sft.cern.ch/lcg/external/Python/2.7.4/x86_64-slc6-gcc48-opt/lib/python2.7/Queue.py", line 177, in get
  File "/cvmfs/sft.cern.ch/lcg/external/Python/2.7.4/x86_64-slc6-gcc48-opt/lib/python2.7/threading.py", line 354, in wait
<type 'exceptions.TypeError'>: 'NoneType' object is not callable
Exception in thread GANGA_Update_Thread_Ganga_Worker_2 (most likely raised during interpreter shutdown):
Traceback (most recent call last):
  File "/cvmfs/sft.cern.ch/lcg/external/Python/2.7.4/x86_64-slc6-gcc48-opt/lib/python2.7/threading.py", line 810, in __bootstrap_inner
  File "/cvmfs/sft.cern.ch/lcg/external/Python/2.7.4/x86_64-slc6-gcc48-opt/lib/python2.7/threading.py", line 763, in run
  File "/home/egede/Ganga/install/ganga/python/Ganga/Core/GangaThread/WorkerThreads/WorkerThreadPool.py", line 78, in __worker_thread
  File "/cvmfs/sft.cern.ch/lcg/external/Python/2.7.4/x86_64-slc6-gcc48-opt/lib/python2.7/Queue.py", line 177, in get
  File "/cvmfs/sft.cern.ch/lcg/external/Python/2.7.4/x86_64-slc6-gcc48-opt/lib/python2.7/threading.py", line 354, in wait
<type 'exceptions.TypeError'>: 'NoneType' object is not callable
Exception in thread GANGA_Update_Thread_Ganga_Worker_1 (most likely raised during interpreter shutdown):
Traceback (most recent call last):
  File "/cvmfs/sft.cern.ch/lcg/external/Python/2.7.4/x86_64-slc6-gcc48-opt/lib/python2.7/threading.py", line 810, in __bootstrap_inner
  File "/cvmfs/sft.cern.ch/lcg/external/Python/2.7.4/x86_64-slc6-gcc48-opt/lib/python2.7/threading.py", line 763, in run
  File "/home/egede/Ganga/install/ganga/python/Ganga/Core/GangaThread/WorkerThreads/WorkerThreadPool.py", line 78, in __worker_thread
  File "/cvmfs/sft.cern.ch/lcg/external/Python/2.7.4/x86_64-slc6-gcc48-opt/lib/python2.7/Queue.py", line 177, in get
  File "/cvmfs/sft.cern.ch/lcg/external/Python/2.7.4/x86_64-slc6-gcc48-opt/lib/python2.7/threading.py", line 354, in wait
<type 'exceptions.TypeError'>: 'NoneType' object is not callable
```

**Comment by egede** [comment]
The exception in Python 2.7 also happened when nothing was happening. There were zero jobs to be monitored.

**Comment by rob-c** [comment]
OK, it appears we're not correctly join-ing the queues system threads on shutdown, I've got a PR I'll finish and put in tomorrow which can be merged with the release branch

**Comment by egede** [comment]
@milliams We need to have the PR for this in before 6.1.17 is out. 

@rob-c As far as I understand the exception is always thrown when the thread is not processing anything, so in that sense it should be safe to catch the exception and then break out of the while loop.

**Comment by milliams** [comment]
Yes, this looks like the threads are not being joined correctly and so they are running after the interpreter has started clearing out the global namespace.
