### ISSUE TITLE
Corrupt jobs throwing an exception which causes Ganga to not load

### ISSUE THREAD

**Issue by rob-c** [ganga-devs/ganga#32]
Hi all,

Apparently I wasn't able to catch all possible situations where a corrupt job causes Ganga to fail to load due to a repository error.

I'll work on this for 6.1.14. I think the problem is the 'catch all' except here was written with GangaExceptions in mind I think.

I'll look into wrapping the errors from SubJobXML and the VStreamer as part of this release into better defined errors.

Rob

Original exception thrown from Chris Jones below:

```
Welcome to Ganga ***
Version: 6.1.13
Documentation and support: http://cern.ch/ganga
Type help() or help('index') for online help.
This is free software (GPL), and you are welcome to redistribute it
under certain conditions; type license() for details.
Ganga.Utility.Config : INFO reading config file /cvmfs/lhcb.cern.ch/lib/lhcb/GANGA/GANGA_v601r13/install/ganga/python/GangaLHCb/LHCb.ini
Ganga.Utility.Config : INFO reading config file /lhcb/GangaCambridge/lhcb/config/6-0-8/GangaLHCb.ini
Ganga.Utility.Config : INFO reading config file /usera/jonesc/.gangarc
Traceback (most recent call last):
File "/cvmfs/lhcb.cern.ch/lib/lhcb/GANGA/GANGA_v601r13/install/ganga/bin/ganga", line 49, in <module>
Ganga.Runtime._prog.bootstrap()
File "/cvmfs/lhcb.cern.ch/lib/lhcb/GANGA/GANGA_v601r13/install/ganga/python/Ganga/Runtime/bootstrap.py", line 1113, in bootstrap
for n, k, d in Repository_runtime.bootstrap():
File "/cvmfs/lhcb.cern.ch/lib/lhcb/GANGA/GANGA_v601r13/install/ganga/python/Ganga/Runtime/Repository_runtime.py", line 123, in bootstrap
registry.startup()
File "/cvmfs/lhcb.cern.ch/lib/lhcb/GANGA/GANGA_v601r13/install/ganga/python/Ganga/GPIDev/Lib/Registry/JobRegistry.py", line 86, in startup
super(JobRegistry, self).startup()
File "/cvmfs/lhcb.cern.ch/lib/lhcb/GANGA/GANGA_v601r13/install/ganga/python/Ganga/Core/GangaRepository/Registry.py", line 536, in startup
self.repository.startup()
File "/cvmfs/lhcb.cern.ch/lib/lhcb/GANGA/GANGA_v601r13/install/ganga/python/Ganga/Core/GangaRepository/GangaRepositoryXML.py", line 173, in startup
self.update_index(verbose=True, firstRun=True)
File "/cvmfs/lhcb.cern.ch/lib/lhcb/GANGA/GANGA_v601r13/install/ganga/python/Ganga/Core/GangaRepository/GangaRepositoryXML.py", line 436, in update_index
logger.debug("Failed to load id %i: %s %s" % (id, getName(x.orig), x.orig))
AttributeError: 'exceptions.KeyError' object has no attribute 'orig'
```

**Comment by rob-c** [comment]
I think this has been addressed at this point as I've spent some time checking the exceptions throughout the XML stack, it should be fixed in develop by now.
