### ISSUE TITLE
Glitch in LSF submission when the job name isn't empty

### ISSUE THREAD

**Issue by olupton** [ganga-devs/ganga#51]
Hi,

If I try and submit a job with the LSF backend, I get an error and the submission fails:

Ganga.GPIDev.Adapters              : INFO     submitting job 14.0 to LSF backend
Ganga.GPIDev.Lib.Job               : INFO     job 14.0 status changed to "submitting"
Ganga.GPIDev.Adapters              : WARNING  ---------- error in user/extension code ----------
Ganga.GPIDev.Adapters              : WARNING  Traceback (most recent call last):
Ganga.GPIDev.Adapters              : WARNING    File "/afs/cern.ch/lhcb/software/releases/GANGA/GANGA_v601r13/install/ganga/python/Ganga/GPIDev/Adapters/IBackend.py", line 179, in master_submit
Ganga.GPIDev.Adapters              : WARNING      if b.submit(sc, master_input_sandbox):
Ganga.GPIDev.Adapters              : WARNING    File "/afs/cern.ch/lhcb/software/releases/GANGA/GANGA_v601r13/install/ganga/python/Ganga/Lib/Batch/Batch.py", line 165, in submit
Ganga.GPIDev.Adapters              : WARNING      if isType(self, PBS):
Ganga.GPIDev.Adapters              : WARNING  NameError: global name 'isType' is not defined
Ganga.GPIDev.Adapters              : WARNING  --------------------------------------------------
Ganga.GPIDev.Lib.Job               : ERROR    JobManagerError: error during submit
Ganga.GPIDev.Lib.Job               : ERROR    JobManagerError: error during submit ... reverting job 14 to the new status
Ganga.GPIDev.Lib.Job               : INFO     job 14 status changed to "new"
Ganga.Runtime.bootstrap            : ERROR    JobError: Error: JobManagerError: error during submit

This seems to just be a trivial missing import from somewhere? The bug can be avoided by making sure the job name is an empty string.

**Comment by olupton** [comment]
Thanks Matt!
