### ISSUE TITLE
Race condition in monitoring when copying jobs

### ISSUE THREAD

**Issue by milliams** [ganga-devs/ganga#57]
In a clean Ganga session with a completely wiped `~/ganga_dir`, running the following:

```python
j = Job(); j.submit(); j.copy(); j.copy()
```

causes an exception in the monitoring loop about 80% of the time. The exception given is:

```
Traceback (most recent call last):
  File ".../ganga/python/Ganga/GPIDev/Lib/Job/Job.py", line 611, in updateStatus
    self.time.timenow(str(newstatus))
  File ".../ganga/python/Ganga/GPIDev/Lib/Job/JobTime.py", line 127, in timenow
    be_statetime = j.backend.getStateTime(childstatus)
  File ".../ganga/python/Ganga/Lib/Localhost/Localhost.py", line 112, in getStateTime
    j = self.getJobObject()
  File ".../ganga/python/Ganga/GPIDev/Base/Objects.py", line 1025, in getJobObject
    raise AssertionError('no job associated with object ' + repr(self))
AssertionError: no job associated with object <Ganga.Lib.Localhost.Localhost.Localhost object at 0x314c650>
```

Pausing for a second between after the `submit()` operation makes the race condition disappear:

```python
from time import sleep
j = Job(); j.submit(); sleep(1); j.copy(); j.copy()
```

This came up when converting the JIRA1961 test to the new system.

**Comment by rob-c** [comment]
@milliams 

I've a load of fixes I'm meaning to put into the release branch, there is a fix for there I'm wanting to put in before I re-run the unittests, bare with me,

Rob

**Comment by rob-c** [comment]
OK, spoke too soon, this particular bug is new, I fixed a similar one recently. I'll do some digging and see what's causing the problem. Strange it's being thrown from updateStatus.
I can easily add a fix to give a dummy response here while the job is under construction.

**Comment by rob-c** [comment]
@milliams  This wasn't strictly a race condition, despite appearing as such. This was actually a bug which was 100% reproducible within the Core which I should have now fixed as part of the latest set of commits I've put up again today.

I'm going to mark this as closed as it went away in my testing but if you can still reproduce this can you re-open the bug and I'll take a look at it tomorrow,

Thanks,

Rob

**Comment by milliams** [comment]
It looks like that particular bug might have been fixed but the [nightly tests failed](https://ganga-ci.cern.ch/jenkins/job/Nightly/lastCompletedBuild/testReport/TestJob/TestJob/testJobSubmit_2/) with:


```
Traceback (most recent call last):
  File "/usr/lib64/python2.6/unittest.py", line 288, in run
    self.tearDown()
  File "/var/lib/jenkins/workspace/Nightly/python/Ganga/new_tests/GPI/GangaUnitTest.py", line 181, in tearDown
    stopGanga()
  File "/var/lib/jenkins/workspace/Nightly/python/Ganga/new_tests/GPI/GangaUnitTest.py", line 142, in stopGanga
    j.remove()
  File "/var/lib/jenkins/workspace/Nightly/python/Ganga/GPIDev/Lib/Job/Job.py", line 1828, in remove
    self.application.decrementShareCounter(self.application.is_prepared.name)
  File "/var/lib/jenkins/workspace/Nightly/python/Ganga/GPIDev/Adapters/IPrepareApp.py", line 199, in decrementShareCounter
    shareref.decrease(shared_directory_name, remove)
  File "/var/lib/jenkins/workspace/Nightly/python/Ganga/GPIDev/Lib/Registry/PrepRegistry.py", line 164, in decrease
    if self.name[basedir] > 0:
  File "/var/lib/jenkins/workspace/Nightly/python/Ganga/GPIDev/Base/Objects.py", line 477, in __get__
    raise err
GangaException: GangaException:  ('Error finding parameter name in object ShareRef',)
```

It seems to be failing on shutting down Ganga. I can reproduce this in a normal Ganga session too.

**Comment by rob-c** [comment]
Yes, spotted and fixed, new patches incoming

**Comment by alexanderrichards** [comment]
> but the nightly tests failed with:

score one for the new testing infrastructure, already proving it's worth :smile:

**Comment by milliams** [comment]
@alexanderrichards Indeed. I've just set it up so that it should send out an email if the tests fail too. I'm not clear yet *who* the email will be sent to but one should go out in future.

**Comment by alexanderrichards** [comment]
I guess it would probably be the developers list?

**Comment by rob-c** [comment]
OK, there is some more code on top of the release branch which should address this issue.

**Comment by milliams** [comment]
Ok, my tests are all passing again.
