### ISSUE TITLE
DiracFile on Dirac backend with GaudiRun app

### ISSUE THREAD

**Issue by mesmith75** [ganga-devs/ganga#626]
The output DiracFile does not work when submitting to Dirac backend.
It is fine for the Local backend and LocalFile submits ok to both Local and Dirac backend.
The error is:
```
ERROR    Error submitting job to Dirac: Traceback (most recent call last):
  File "<stdin>", line 470, in <module>                                                                                                                     
  File "<string>", line 453, in <module>                                                                                                                    
  File "/afs/cern.ch/work/m/masmith/gangadir/workspace/masmith/LocalXML/956/input/dirac-script.py", line 17, in <module>                                    
    j.setOutputData(['test_10ev.root'], outputPath='', outputSE=[])                                                                                         
TypeError: setOutputData() got an unexpected keyword argument 'outputPath'                                                                                  

ERROR   

===                                                                                                                                                         
/afs/cern.ch/work/m/masmith/gangadir/workspace/masmith/LocalXML/956/input/dirac-script.py                                                                   
===                                                                                                                                                         

ERROR   

====                                                                                                                                                        

ERROR   
# dirac job created by ganga                                                                                                                                
from DIRAC.Core.Base.Script import parseCommandLine                                                                                                         
parseCommandLine()                                                                                                                                          
from LHCbDIRAC.Interfaces.API.DiracLHCb import DiracLHCb                                                                                                    
from LHCbDIRAC.Interfaces.API.LHCbJob import LHCbJob                                                                                                        
dirac = DiracLHCb()                                                                                                                                         
j = LHCbJob()                                                                                                                                               

# default commands added by ganga                                                                                                                           
j.setName('Brunel_Nov2012_ghostFit_5_cmakeTest__{Ganga_GaudiRun_(956)}')
j.setExecutable('gaudiRun-script.py','','Ganga_GaudiRun.log')
j.setInputSandbox(['LFN:/lhcb/user/m/masmith/GangaInputFile/Job_956/__conf-3d62e484-81ea-4aeb-8d21-35fbd659f099.tgz'])
j.setOutputSandbox(['__postprocesslocations__'])
j.setInputData(['LFN:/lhcb/LHCb/Collision12/BHADRONCOMPLETEEVENT.DST/00021211/0001/00021211_00010037_1.bhadroncompleteevent.dst'])

j.setOutputData(['test_10ev.root'], outputPath='', outputSE=[])


# <-- user settings
j.setCPUTime(172800)

# user settings -->

# diracOpts added by user


# submit the job to dirac
j.setPlatform( 'ANY' )
result = dirac.submit(j)
output(result)
ERROR   
====

ERROR    BackendError: Error submitting job to Dirac: Traceback (most recent call last):
  File "<stdin>", line 470, in <module>
  File "<string>", line 453, in <module>
  File "/afs/cern.ch/work/m/masmith/gangadir/workspace/masmith/LocalXML/956/input/dirac-script.py", line 17, in <module>
    j.setOutputData(['test_10ev.root'], outputPath='', outputSE=[])
TypeError: setOutputData() got an unexpected keyword argument 'outputPath'
 (Dirac backend)
ERROR    JobManagerError: error during submit
ERROR    JobManagerError: error during submit ... reverting job 956 to the new status
```

**Comment by alexanderrichards** [comment]
interesting, has the DIRAC API changed?

**Comment by rob-c** [comment]
@mesmith75 What application are you using? This could be serious enough to warrant a fix for 6.1.21 if there's a bigger problem here.

**Comment by egede** [comment]
@rob-c I believe this is with the new `GaudiRun` application.

@mesmith75 Can you compare the lines above to the lines that are written if you submit an old-style `DaVinci` job?

**Comment by alexanderrichards** [comment]
> @mesmith75 Can you compare the lines above to the lines that are written if you submit an old-style DaVinci job?

These lines are written to your job script in your inputwork dir

**Comment by rob-c** [comment]
@alexanderrichards I suspect this is a bug in the GaudiRun app which I'm working on for other issues anyway

**Comment by mesmith75** [comment]
Sorry, I forgot to say, this is for testing the new GaudiRun app.

**Comment by mesmith75** [comment]
For the relevant line there is just a change in the capitalisation compared to an old job:
j.setOutputData(['DVNtuples.root'],OutputPath='',OutputSE=[],replicate='')

**Comment by alexanderrichards** [comment]
as I recall this is a difference that had to be reflected in the LHCb package as LHCbDIRAC has this different capitalisation to vanilla DIRAC. I assume therefore that this bug has been introduced in some of the cleanup work for DIRAC. It's unfortunate that there is this difference between LHCbDIRAC and vanilla but if your looking at this @rob-c it might be worth checking that the situation is still as I have described as otherwise we can remove the specialisation for LHCbDirac

**Comment by mesmith75** [comment]
@alexanderrichards I think you were right. In GaudiRunAppHandlers I switched dirac_outputfiles = lhcbdirac_outputfile_jdl(outputfiles, False) which comes from regular Dirac ( GangaDirac.Lib.RTHandlers.DiracRTHUtils ) to dirac_outputfiles = lhcbdirac_outputfile_jdl(outputfiles) from LHCb Dirac (GangaLHCb.Lib.RTHandlers.RTHUtils) as per the other LHCb applications and it seems to work for me.

I think it is functionally the same - the LHCb looks to just use the standard Dirac one and then replace some words: outputPath -> OutputPath , outputSE->OutputSE and 
###OUTPUT_SE### ->###OUTPUT_SE###,replicate=\'###REPLICATE###\'

**Comment by alexanderrichards** [comment]
indeed this is what I recalled. Alas unless we can get them to change their API we are stuck with this.

**Comment by rob-c** [comment]
This is an API bug in GaudiRun's handler, fix in another PR...
