### ISSUE TITLE
GaudiRun support for simple splitting of jobs

### ISSUE THREAD

**Issue by pseyfert** [ganga-devs/ganga#688]
As far as I can tell, GaudiRun doesn't work in ganga v6.1.22 with `SplitByFiles` (i.e. making ntuples)

# As minimum failing "hello world" example:
on the shell
```
cd /afs/cern.ch/work/p/pseyfert
rm -rf DaVinciDev_v41r0/
lb-dev DaVinci v41r0
cd ./DaVinciDev_v41r0
make
make install
SetupGanga
lhcb-proxy-init
# enter password
ganga
```
and then in ganga
```
with open("/tmp/pseyfert/dummy.py",'w') as f:
        f.write("print \"hello world\"")

dtpath = "/LHCb/Collision15/Beam6500GeV-VeloClosed-MagDown/Real Data/Reco15a/Stripping24/90000000/SEMILEPTONIC.DST"
data = BKQuery(path=dtpath).getDataset()

job = Job(application = GaudiRun())
job.application.directory = "/afs/cern.ch/work/p/pseyfert/DaVinciDev_v41r0"
job.application.myOpts = "/tmp/pseyfert/dummy.py"
job.name = "GaudiRun_test"
job.inputdata  = data
job.backend = Dirac()
job.splitter = SplitByFiles(filesPerJob = 5, maxFiles = 20)
job.submit()
```
_fails here_
ganga responds to that with
```
Ganga In [11]: job.submit()
INFO     submitting job 2647
INFO     job 2647 status changed to "submitting"
INFO     Preparing GaudiRun application.
INFO     Created shared directory: conf-da991028-53bf-4844-a448-6b5c510e4e7b
INFO     Make-ing target 'ganga-input-sandbox'     (This may take a few minutes depending on the size of your project)
INFO     full cmd: export CMTCONFIG=x86_64-slc6-gcc49-opt; source LbLogin.sh --cmtconfig=x86_64-slc6-gcc49-opt && make && ./run bash -c "make ganga-input-sandbox"
INFO     Running: bash /tmp/pseyfert/tmpAOsP2l.sh
INFO     Built /afs/cern.ch/work/p/pseyfert/DaVinciDev_v41r0/build.x86_64-slc6-gcc49-opt/ganga/cmake-input-sandbox.tgz
ERROR    [Errno 21] Is a directory: '/afs/cern.ch/work/p/pseyfert/DaVinciDev_v41r0'
INFO     Splitting Job: 2647
INFO     Constructing subjobs
INFO     Requesting LFN replica info
INFO     Got Replica Info: [0:20] of 20
INFO     Got replicas
INFO     found all replicas
INFO     Calculating site<->SE Mapping
INFO     Calculating best data subsets
INFO     Average Subset size is: 2.85714285714
INFO     File count checked! Ready to Submit
INFO     Created 7 subsets
INFO     Finished Splitting
INFO     submitting 7 subjobs



WARNING  This GaudiRun Application is still in the testing phase.
WARNING  There is no guarantee that any jobs submitted with it wil remain compatible with the next release of Ganga
Please Hit the return key to continue with your Job submission

INFO     Constructing: /afs/cern.ch/user/p/pseyfert/gangadir/shared/pseyfert/conf-da991028-53bf-4844-a448-6b5c510e4e7b/__timestamp__
INFO     new File: DiracFile(namePattern='__conf-da991028-53bf-4844-a448-6b5c510e4e7b.tgz', lfn='', localDir='/afs/cern.ch/user/p/pseyfert/gangadir/shared/pseyfert/conf-da991028-53bf-4844-a448-6b5c510e4e7b')
INFO     Uploading file '/afs/cern.ch/user/p/pseyfert/gangadir/shared/pseyfert/conf-da991028-53bf-4844-a448-6b5c510e4e7b/__conf-da991028-53bf-4844-a448-6b5c510e4e7b.tgz' to 'CNAF-USER' as '/lhcb/user/p/pseyfert/GangaInputFile/Job_2647/__conf-da991028-53bf-4844-a448-6b5c510e4e7b.tgz'
INFO     Preparing subjobs
WARNING  ---------- error in user/extension code ----------
WARNING  Traceback (most recent call last):
WARNING    File "/afs/cern.ch/lhcb/software/releases/GANGA/GANGA_v601r22/install/ganga/python/Ganga/GPIDev/Lib/Job/Job.py", line 1524, in submit
WARNING      jobsubconfig = self._getJobSubConfig(rjobs)
WARNING    File "/afs/cern.ch/lhcb/software/releases/GANGA/GANGA_v601r22/install/ganga/python/Ganga/GPIDev/Lib/Job/Job.py", line 1252, in _getJobSubConfig
WARNING      jobsubconfig = [rtHandler.prepare(sub_job.application, sub_conf, appmasterconfig, jobmasterconfig) for (sub_job, sub_conf) in zip(subjobs, appsubconfig)]
WARNING    File "/afs/cern.ch/lhcb/software/releases/GANGA/GANGA_v601r22/install/ganga/python/GangaLHCb/Lib/GaudiRunApp/GaudiRunAppHandlers.py", line 313, in prepare
WARNING      if not job.master.app.uploadedInput:
WARNING  AttributeError: 'Job' object has no attribute 'app'
WARNING  --------------------------------------------------
ERROR    'Job' object has no attribute 'app' ... reverting job 2647 to the new status
INFO     job 2647 status changed to "new"
ERROR    Error: JobError: Error: 'Job' object has no attribute 'app'
```

# cross check:
open a new shell on the same node to verify that the job works locally
```
cd /afs/cern.ch/work/p/pseyfert/DaVinciDev_v41r0
./run gaudirun.py /tmp/pseyfert/dummy.py
```
output:
```
# --> Including file '/tmp/pseyfert/dummy.py'
hello world
# <-- End of file '/tmp/pseyfert/dummy.py'
ApplicationMgr    SUCCESS 
====================================================================================================================================
                                                   Welcome to DaVinciDev version v41r0
                                          running on lxplus032.cern.ch on Thu Jul 21 17:01:17 2016
====================================================================================================================================
ApplicationMgr       INFO Application Manager Configured successfully
HistogramPersis...WARNING Histograms saving not required.
ApplicationMgr       INFO Application Manager Initialized successfully
ApplicationMgr       INFO Application Manager Started successfully
EventSelector        INFO End of event input reached.
EventLoopMgr         INFO No more events in event selection 
ApplicationMgr       INFO Application Manager Stopped successfully
EventLoopMgr         INFO Histograms converted successfully according to request.
ToolSvc              INFO Removing all tools created by ToolSvc
ApplicationMgr       INFO Application Manager Finalized successfully
ApplicationMgr       INFO Application Manager Terminated successfully
```
and check it's return code
```
> echo $?
0
```

# cross check 2 (narrow down that it's actually due to splitting):
```
data.files = data.files[0:1]
job = Job(application = GaudiRun())
job.application.directory = "/afs/cern.ch/work/p/pseyfert/DaVinciDev_v41r0"
job.application.myOpts = "/tmp/pseyfert/dummy.py"
job.name = "GaudiRun_test"
job.inputdata  = data
job.backend = Dirac()
job.splitter = None
job.submit()
```
submits fine

# PS
tried on lxplus; with ganga from afs and cvmfs; in bash and zsh;

**Comment by rob-c** [comment]
@pseyfert Thanks for filing an issue.
I'm currently working on making a lot of very low level changes to the GaudiRun application. This will work in the next release but the schema has been completely rewritten and the application may even change it's name before 6.1.23.
Rob

**Comment by rob-c** [comment]
This appears to be working now in `GaudiExec` which inherits from and supersedes `GaudiRun` in 6.1.23
