### ISSUE TITLE
error when setting twice the input files

### ISSUE THREAD

**Issue by cmarinbe** [ganga-devs/ganga#844]
I'm using Ganga v602r2 and got the following error when preparing a DaVinci job:
```
INFO     Job 15: Preparing DaVinci application.
WARNING  Found inputdataset defined in optsfile, this will get pickled up and stored in the prepared state. Any change to the options/data will therefore require an unprepare first.
WARNING  NOTE: the prefered way of working is to define inputdata in the job.inputdata field. 
WARNING  Data defined in job.inputdata will superseed optsfile data!
WARNING  Inputdata can be transfered from optsfiles to the job.inputdata field using job.inputdata = job.application.readInputData(optsfiles)
Traceback (most recent call last):
 File "/afs/cern.ch/lhcb/software/releases/GANGA/GANGA_v602r2/install/ganga/bin/ganga", line 69, in <module>
   Ganga.Runtime._prog.run()
 File "/afs/cern.ch/lhcb/software/releases/GANGA/GANGA_v602r2/install/ganga/python/Ganga/Runtime/bootstrap.py", line 1086, in run
   execfile(script, local_ns)
 File "submit_job.py", line 69, in <module>
   j = dv_job(name, optfiles, query, mag)
 File "submit_job.py", line 34, in dv_job
   j.prepare()
 File "/afs/cern.ch/lhcb/software/releases/GANGA/GANGA_v602r2/install/ganga/python/Ganga/GPIDev/Base/Proxy.py", line 668, in proxy_wrapped
   r = f(*s_args, **s_kwargs)
 File "/afs/cern.ch/lhcb/software/releases/GANGA/GANGA_v602r2/install/ganga/python/Ganga/GPIDev/Lib/Job/Job.py", line 1121, in prepare
   add_to_inputsandbox = addProxy(self.application).prepare()
 File "/afs/cern.ch/lhcb/software/releases/GANGA/GANGA_v602r2/install/ganga/python/Ganga/GPIDev/Base/Proxy.py", line 668, in proxy_wrapped
   r = f(*s_args, **s_kwargs)
 File "/afs/cern.ch/lhcb/software/releases/GANGA/GANGA_v602r2/install/ganga/python/GangaGaudi/Lib/Applications/Gaudi.py", line 153, in prepare
   self._parse_options()
 File "<string>", line 1262, in _parse_options
 File "/afs/cern.ch/sw/lcg/releases/LCG_79/Python/2.7.9.p1/x86_64-slc6-gcc48-opt/lib/python2.7/pickle.py", line 1370, in dump
   Pickler(file, protocol).dump(obj)
 File "/afs/cern.ch/sw/lcg/releases/LCG_79/Python/2.7.9.p1/x86_64-slc6-gcc48-opt/lib/python2.7/pickle.py", line 224, in dump
   self.save(obj)
 File "/afs/cern.ch/sw/lcg/releases/LCG_79/Python/2.7.9.p1/x86_64-slc6-gcc48-opt/lib/python2.7/pickle.py", line 306, in save
   rv = reduce(self.proto)
 File "/afs/cern.ch/sw/lcg/releases/LCG_79/Python/2.7.9.p1/x86_64-slc6-gcc48-opt/lib/python2.7/copy_reg.py", line 77, in _reduce_ex
   raise TypeError("a class that defines __slots__ without "
TypeError: a class that defines __slots__ without defining __getstate__ cannot be pickled
```
The warnings are very useful (I had really forgotten to remove the input file I was using for local tests from the options file) but I think this should not end in an error. If I recall properly it was not so in previous versions. Jibo checked this only happens for CMT jobs but not for the new GaudiExec jobs. Let me know if you need any more info.

**Comment by egede** [comment]
@cmarinbe Thanks for the bug report. The support for the old CMT style applications have stopped so I will not promise a fix for this unless it is really trivial. There are obviously 3 workarounds at the moment (migrate to using GaudiExec, take the data out of the opts file, or use and earlier Ganga release).

**Comment by cmarinbe** [comment]
So the recommendation now is to use GaudiExec even if you don't need any private packages? If so, this should really not be a problem.

**Comment by egede** [comment]
@rob-c Has the problem with GaudiExec (when no packages are checked out) been fixed?

**Comment by rob-c** [comment]
@egede It appears to be now, I get a target and no compilation errors. Although I've not submitted any complex test jobs.

**Comment by egede** [comment]
@cmarinbe So using `GaudiExec` I think indeed is the recommendation for everything (I am aware of a problem with the `readInputData` (#841) but that is about all.

**Comment by cmarinbe** [comment]
Ok, thanks for the info @egede !

**Comment by rob-c** [comment]
@egede Are we OK to close this as won't fix or is this something worth looking into?
