### ISSUE TITLE
LHCbDataset breaks Tasks

### ISSUE THREAD

**Issue by olupton** [ganga-devs/ganga#858]
Hi,

In the latest release for LHCb (v602r2) Tasks are not usable. At first glance this is because of a bug in LHCbDataset where it tests for DiracFile too late:
https://github.com/ganga-devs/ganga/blob/master/python/GangaLHCb/Lib/LHCbDataset/LHCbDataset.py#L221

This causes:
```
ERROR    Exception occurred in task monitoring loop: <type 'exceptions.AttributeError'> 'list' object has no attribute 'namePattern'
The offending task was paused.
ERROR    Full traceback:
 Traceback (most recent call last):
   File "/afs/cern.ch/lhcb/software/releases/GANGA/GANGA_v602r2/install/ganga/python/Ganga/GPIDev/Lib/Tasks/TaskRegistry.py", line 92, in _thread_main
    p.update()
   File "/afs/cern.ch/lhcb/software/releases/GANGA/GANGA_v602r2/install/ganga/python/Ganga/GPIDev/Lib/Tasks/ITask.py", line 99, in update
    if trf.update() and not self.check_all_trfs:
   File "/afs/cern.ch/lhcb/software/releases/GANGA/GANGA_v602r2/install/ganga/python/Ganga/GPIDev/Lib/Tasks/ITransform.py", line 235, in update
    self.createUnits()
   File "/afs/cern.ch/lhcb/software/releases/GANGA/GANGA_v602r2/install/ganga/python/GangaLHCb/Lib/Tasks/LHCbTransform.py", line 120, in createUnits
    new_data = LHCbDataset( files = self.inputdata[id].difference(assigned_data).files )
   File "/afs/cern.ch/lhcb/software/releases/GANGA/GANGA_v602r2/install/ganga/python/GangaLHCb/Lib/LHCbDataset/LHCbDataset.py", line 381, in difference
    data.extend([list(files)])
   File "/afs/cern.ch/lhcb/software/releases/GANGA/GANGA_v602r2/install/ganga/python/GangaLHCb/Lib/LHCbDataset/LHCbDataset.py", line 221, in extend
    myName = _file.namePattern
 AttributeError: 'list' object has no attribute 'namePattern'
```

...and, seeing as I don't see a way around this, makes Tasks unusable in the current version...?

**Comment by mesmith75** [comment]
@olupton This looks to be because the task is using the difference function in LHCbDataset. There was a bug in this which has been fixed (#856) for the next Ganga version, due imminently.

The last version this worked on was I think v601r22.

**Comment by olupton** [comment]
Thanks @mesmith75 -- I'll have a try with v601r22.
Sorry for not noticing it had been fixed -- I guess the 'master' branch is not the state of the art.

**Comment by mesmith75** [comment]
ah yes - everything goes into the develop branch, so you can try that if you want the latest version. Just be aware that v601r22 was pre GaudiExec.

**Comment by olupton** [comment]
Thanks @mesmith75  -- v601r22 works for now. Fortunately I didn't need GaudiExec in this case.
